// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createIdentity = `-- name: CreateIdentity :exec
INSERT INTO identities (provider, subject, user_id) VALUES ($1, $2, $3)
`

type CreateIdentityParams struct {
	Provider string
	Subject  string
	UserID   uuid.UUID
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity, arg.Provider, arg.Subject, arg.UserID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, role, locale) VALUES ($1, $2, $3) RETURNING id, name, role, locale, created_at, active_exam
`

type CreateUserParams struct {
	Name   string
	Role   string
	Locale string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Role, arg.Locale)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Locale,
		&i.CreatedAt,
		&i.ActiveExam,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, role, locale, created_at, active_exam FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Locale,
		&i.CreatedAt,
		&i.ActiveExam,
	)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT u.id, u.name, u.role, u.locale, u.created_at, u.active_exam
FROM identities i
JOIN users u ON u.id = i.user_id
WHERE i.provider = $1 AND i.subject = $2
`

type GetUserByIdentityParams struct {
	Provider string
	Subject  string
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Provider, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Locale,
		&i.CreatedAt,
		&i.ActiveExam,
	)
	return i, err
}

const listIdentities = `-- name: ListIdentities :many
SELECT provider, created_at FROM identities
WHERE user_id = $1 AND provider <> 'dev'
ORDER BY created_at
`

type ListIdentitiesRow struct {
	Provider  string
	CreatedAt time.Time
}

func (q *Queries) ListIdentities(ctx context.Context, userID uuid.UUID) ([]ListIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIdentitiesRow{}
	for rows.Next() {
		var i ListIdentitiesRow
		if err := rows.Scan(&i.Provider, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users SET role = $2 WHERE id = $1
`

type SetUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.ID, arg.Role)
	return err
}
