// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_errors.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteOldClientErrors = `-- name: DeleteOldClientErrors :execrows
DELETE FROM client_errors WHERE received_at < now() - interval '90 days'
`

// Старше 90 дней ошибки клиентов не нужны: таблица не растёт без конца.
func (q *Queries) DeleteOldClientErrors(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldClientErrors)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertClientError = `-- name: InsertClientError :exec
INSERT INTO client_errors (user_id, request_id, message, stack, route, client_kind, app_version, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertClientErrorParams struct {
	UserID     *uuid.UUID
	RequestID  *string
	Message    string
	Stack      *string
	Route      *string
	ClientKind string
	AppVersion string
	OccurredAt time.Time
}

func (q *Queries) InsertClientError(ctx context.Context, arg InsertClientErrorParams) error {
	_, err := q.db.Exec(ctx, insertClientError,
		arg.UserID,
		arg.RequestID,
		arg.Message,
		arg.Stack,
		arg.Route,
		arg.ClientKind,
		arg.AppVersion,
		arg.OccurredAt,
	)
	return err
}
