// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exams.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listExamSections = `-- name: ListExamSections :many
SELECT exam_id, section FROM exam_sections ORDER BY exam_id, position
`

type ListExamSectionsRow struct {
	ExamID  string
	Section string
}

func (q *Queries) ListExamSections(ctx context.Context) ([]ListExamSectionsRow, error) {
	rows, err := q.db.Query(ctx, listExamSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExamSectionsRow{}
	for rows.Next() {
		var i ListExamSectionsRow
		if err := rows.Scan(&i.ExamID, &i.Section); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveExam = `-- name: SetActiveExam :exec
UPDATE users SET active_exam = $1::text WHERE id = $2
`

type SetActiveExamParams struct {
	ExamID string
	UserID uuid.UUID
}

func (q *Queries) SetActiveExam(ctx context.Context, arg SetActiveExamParams) error {
	_, err := q.db.Exec(ctx, setActiveExam, arg.ExamID, arg.UserID)
	return err
}
