// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type ClientError struct {
	ID         int64
	UserID     *uuid.UUID
	RequestID  *string
	Message    string
	Stack      *string
	Route      *string
	ClientKind string
	AppVersion string
	OccurredAt time.Time
	ReceivedAt time.Time
}

type Identity struct {
	Provider  string
	Subject   string
	UserID    uuid.UUID
	CreatedAt time.Time
}

type Question struct {
	ID           uuid.UUID
	QuestionType string
	TopicID      string
	Difficulty   string
	Status       string
	Body         []byte
	Answer       []string
	Explanation  []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type QuestionReport struct {
	ID         int64
	UserID     *uuid.UUID
	QuestionID uuid.UUID
	TrainingID *uuid.UUID
	Kind       string
	Text       *string
	CreatedAt  time.Time
	ResolvedAt *time.Time
}

type Session struct {
	TokenHash         []byte
	UserID            uuid.UUID
	ClientKind        string
	CreatedAt         time.Time
	LastSeenAt        time.Time
	IdleExpiresAt     time.Time
	AbsoluteExpiresAt time.Time
}

type Topic struct {
	ID       string
	Section  string
	TitleRu  string
	TitleEn  string
	Position int
}

type Training struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Mode             string
	Section          string
	QuestionTypes    []string
	Request          []byte
	TimeLimitSeconds *int
	StartedAt        time.Time
	FinishedAt       *time.Time
	TimedOut         bool
}

type TrainingItem struct {
	TrainingID uuid.UUID
	Position   int
	QuestionID uuid.UUID
	OptionIds  []string
	DontKnow   bool
	Flagged    bool
	AnsweredAt *time.Time
	ElapsedMs  *int
	Correct    *bool
}

type User struct {
	ID        uuid.UUID
	Name      string
	Role      string
	Locale    string
	CreatedAt time.Time
}
