// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, client_kind, idle_expires_at, absolute_expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	TokenHash         []byte
	UserID            uuid.UUID
	ClientKind        string
	IdleExpiresAt     time.Time
	AbsoluteExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.ClientKind,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE idle_expires_at <= now() OR absolute_expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getLiveSession = `-- name: GetLiveSession :one
SELECT s.token_hash, s.last_seen_at, s.idle_expires_at, u.id, u.name, u.role, u.locale, u.created_at, u.active_exam
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.idle_expires_at > now()
  AND s.absolute_expires_at > now()
`

type GetLiveSessionRow struct {
	TokenHash     []byte
	LastSeenAt    time.Time
	IdleExpiresAt time.Time
	ID            uuid.UUID
	Name          string
	Role          string
	Locale        string
	CreatedAt     time.Time
	ActiveExam    *string
}

// Сессия жива, только если не истекли оба срока: простоя и абсолютный.
func (q *Queries) GetLiveSession(ctx context.Context, tokenHash []byte) (GetLiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getLiveSession, tokenHash)
	var i GetLiveSessionRow
	err := row.Scan(
		&i.TokenHash,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Locale,
		&i.CreatedAt,
		&i.ActiveExam,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = now(),
    idle_expires_at = least($1::timestamptz, absolute_expires_at)
WHERE token_hash = $2
`

type TouchSessionParams struct {
	IdleExpiresAt time.Time
	TokenHash     []byte
}

// Продление простоя — не дальше абсолютного срока.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.IdleExpiresAt, arg.TokenHash)
	return err
}
