// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trainings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countApprovedQuestions = `-- name: CountApprovedQuestions :many
SELECT t.section, q.question_type, t.id AS topic_id, t.title_ru, t.title_en, q.difficulty, count(*)::integer AS available
FROM questions q
JOIN topics t ON t.id = q.topic_id
WHERE q.status = 'approved'
GROUP BY t.section, q.question_type, t.id, t.title_ru, t.title_en, t.position, q.difficulty
ORDER BY t.position, t.id
`

type CountApprovedQuestionsRow struct {
	Section      string
	QuestionType string
	TopicID      string
	TitleRu      string
	TitleEn      string
	Difficulty   string
	Available    int
}

// Сколько проверенных заданий в каждой теме по типу и сложности — для конструктора (макеты R1, R2).
func (q *Queries) CountApprovedQuestions(ctx context.Context) ([]CountApprovedQuestionsRow, error) {
	rows, err := q.db.Query(ctx, countApprovedQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountApprovedQuestionsRow{}
	for rows.Next() {
		var i CountApprovedQuestionsRow
		if err := rows.Scan(
			&i.Section,
			&i.QuestionType,
			&i.TopicID,
			&i.TitleRu,
			&i.TitleEn,
			&i.Difficulty,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTraining = `-- name: CreateTraining :one
INSERT INTO trainings (user_id, mode, section, question_types, request, time_limit_seconds, started_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, mode, section, question_types, request, time_limit_seconds, started_at, finished_at, timed_out
`

type CreateTrainingParams struct {
	UserID           uuid.UUID
	Mode             string
	Section          string
	QuestionTypes    []string
	Request          []byte
	TimeLimitSeconds *int
	StartedAt        time.Time
}

func (q *Queries) CreateTraining(ctx context.Context, arg CreateTrainingParams) (Training, error) {
	row := q.db.QueryRow(ctx, createTraining,
		arg.UserID,
		arg.Mode,
		arg.Section,
		arg.QuestionTypes,
		arg.Request,
		arg.TimeLimitSeconds,
		arg.StartedAt,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Mode,
		&i.Section,
		&i.QuestionTypes,
		&i.Request,
		&i.TimeLimitSeconds,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TimedOut,
	)
	return i, err
}

const createTrainingItems = `-- name: CreateTrainingItems :exec
INSERT INTO training_items (training_id, position, question_id)
SELECT $1, (p.ord - 1)::smallint, p.question_id
FROM unnest($2::uuid[]) WITH ORDINALITY AS p (question_id, ord)
`

type CreateTrainingItemsParams struct {
	TrainingID  uuid.UUID
	QuestionIds []uuid.UUID
}

func (q *Queries) CreateTrainingItems(ctx context.Context, arg CreateTrainingItemsParams) error {
	_, err := q.db.Exec(ctx, createTrainingItems, arg.TrainingID, arg.QuestionIds)
	return err
}

const finishTraining = `-- name: FinishTraining :exec
UPDATE trainings SET finished_at = $2, timed_out = $3 WHERE id = $1 AND finished_at IS NULL
`

type FinishTrainingParams struct {
	ID         uuid.UUID
	FinishedAt *time.Time
	TimedOut   bool
}

func (q *Queries) FinishTraining(ctx context.Context, arg FinishTrainingParams) error {
	_, err := q.db.Exec(ctx, finishTraining, arg.ID, arg.FinishedAt, arg.TimedOut)
	return err
}

const getLastTrainingRequest = `-- name: GetLastTrainingRequest :one
SELECT request FROM trainings WHERE user_id = $1 ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) GetLastTrainingRequest(ctx context.Context, userID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getLastTrainingRequest, userID)
	var request []byte
	err := row.Scan(&request)
	return request, err
}

const getTopicSection = `-- name: GetTopicSection :one
SELECT section FROM topics WHERE id = $1
`

func (q *Queries) GetTopicSection(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getTopicSection, id)
	var section string
	err := row.Scan(&section)
	return section, err
}

const getTraining = `-- name: GetTraining :one
SELECT id, user_id, mode, section, question_types, request, time_limit_seconds, started_at, finished_at, timed_out FROM trainings WHERE id = $1 AND user_id = $2
`

type GetTrainingParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Своя тренировка; чужая не находится, как и несуществующая.
func (q *Queries) GetTraining(ctx context.Context, arg GetTrainingParams) (Training, error) {
	row := q.db.QueryRow(ctx, getTraining, arg.ID, arg.UserID)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Mode,
		&i.Section,
		&i.QuestionTypes,
		&i.Request,
		&i.TimeLimitSeconds,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TimedOut,
	)
	return i, err
}

const insertQuestionReport = `-- name: InsertQuestionReport :exec
INSERT INTO question_reports (user_id, question_id, training_id, kind, text) VALUES ($1, $2, $3, $4, $5)
`

type InsertQuestionReportParams struct {
	UserID     *uuid.UUID
	QuestionID uuid.UUID
	TrainingID *uuid.UUID
	Kind       string
	Text       *string
}

func (q *Queries) InsertQuestionReport(ctx context.Context, arg InsertQuestionReportParams) error {
	_, err := q.db.Exec(ctx, insertQuestionReport,
		arg.UserID,
		arg.QuestionID,
		arg.TrainingID,
		arg.Kind,
		arg.Text,
	)
	return err
}

const listTrainingItems = `-- name: ListTrainingItems :many
SELECT i.position, i.question_id, i.option_ids, i.dont_know, i.flagged, i.answered_at, i.elapsed_ms, i.correct,
       q.question_type, q.difficulty, q.body, q.answer, q.explanation,
       t.id AS topic_id, t.section, t.title_ru, t.title_en
FROM training_items i
JOIN questions q ON q.id = i.question_id
JOIN topics t ON t.id = q.topic_id
WHERE i.training_id = $1
ORDER BY i.position
`

type ListTrainingItemsRow struct {
	Position     int
	QuestionID   uuid.UUID
	OptionIds    []string
	DontKnow     bool
	Flagged      bool
	AnsweredAt   *time.Time
	ElapsedMs    *int
	Correct      *bool
	QuestionType string
	Difficulty   string
	Body         []byte
	Answer       []string
	Explanation  []byte
	TopicID      string
	Section      string
	TitleRu      string
	TitleEn      string
}

func (q *Queries) ListTrainingItems(ctx context.Context, trainingID uuid.UUID) ([]ListTrainingItemsRow, error) {
	rows, err := q.db.Query(ctx, listTrainingItems, trainingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrainingItemsRow{}
	for rows.Next() {
		var i ListTrainingItemsRow
		if err := rows.Scan(
			&i.Position,
			&i.QuestionID,
			&i.OptionIds,
			&i.DontKnow,
			&i.Flagged,
			&i.AnsweredAt,
			&i.ElapsedMs,
			&i.Correct,
			&i.QuestionType,
			&i.Difficulty,
			&i.Body,
			&i.Answer,
			&i.Explanation,
			&i.TopicID,
			&i.Section,
			&i.TitleRu,
			&i.TitleEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTraining = `-- name: LockTraining :one
SELECT id, user_id, mode, section, question_types, request, time_limit_seconds, started_at, finished_at, timed_out FROM trainings WHERE id = $1 AND user_id = $2 FOR UPDATE
`

type LockTrainingParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Та же, но под блокировкой: ответы и завершение одной тренировки идут по очереди.
func (q *Queries) LockTraining(ctx context.Context, arg LockTrainingParams) (Training, error) {
	row := q.db.QueryRow(ctx, lockTraining, arg.ID, arg.UserID)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Mode,
		&i.Section,
		&i.QuestionTypes,
		&i.Request,
		&i.TimeLimitSeconds,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TimedOut,
	)
	return i, err
}

const pickQuestions = `-- name: PickQuestions :many
WITH seen AS (
  SELECT DISTINCT i.question_id
  FROM trainings tr
  JOIN training_items i ON i.training_id = tr.id
  WHERE tr.user_id = $6
)
SELECT q.id
FROM questions q
JOIN topics t ON t.id = q.topic_id
LEFT JOIN seen s ON s.question_id = q.id
WHERE q.status = 'approved'
  AND t.section = $1
  AND q.question_type = ANY ($2::text[])
  AND (cardinality($3::text[]) = 0 OR q.topic_id = ANY ($3::text[]))
  AND ($4::text IS NULL OR q.difficulty = $4::text)
ORDER BY s.question_id IS NOT NULL, random()
LIMIT $5::integer
`

type PickQuestionsParams struct {
	Section       string
	QuestionTypes []string
	TopicIds      []string
	Difficulty    *string
	MaxCount      int
	UserID        uuid.UUID
}

// Подбор заданий: только проверенные, сначала те, что человек ещё не видел, внутри — случайно. Виденное —
// по тренировкам самого человека (индекс по user_id), а не по всем показам задания всем людям.
func (q *Queries) PickQuestions(ctx context.Context, arg PickQuestionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, pickQuestions,
		arg.Section,
		arg.QuestionTypes,
		arg.TopicIds,
		arg.Difficulty,
		arg.MaxCount,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const questionReportable = `-- name: QuestionReportable :one
SELECT EXISTS (
  SELECT 1 FROM questions q
  WHERE q.id = $1
    AND (q.status = 'approved' OR EXISTS (
      SELECT 1 FROM training_items i
      JOIN trainings tr ON tr.id = i.training_id
      WHERE i.question_id = q.id AND tr.user_id = $2
    ))
)
`

type QuestionReportableParams struct {
	QuestionID uuid.UUID
	UserID     uuid.UUID
}

// Жаловаться можно на проверенное задание или на то, что было в своей тренировке (его могли снять потом).
func (q *Queries) QuestionReportable(ctx context.Context, arg QuestionReportableParams) (bool, error) {
	row := q.db.QueryRow(ctx, questionReportable, arg.QuestionID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const saveTrainingAnswer = `-- name: SaveTrainingAnswer :execrows
UPDATE training_items
SET option_ids = $1,
    dont_know = $2,
    flagged = $3,
    answered_at = $4,
    elapsed_ms = $5,
    correct = $6
WHERE training_id = $7
  AND position = $8
  AND (answered_at IS NULL OR (NOT $9::boolean AND answered_at <= $4))
`

type SaveTrainingAnswerParams struct {
	OptionIds  []string
	DontKnow   bool
	Flagged    bool
	AnsweredAt *time.Time
	ElapsedMs  *int
	Correct    *bool
	TrainingID uuid.UUID
	Position   int
	KeepFirst  bool
}

// Ответ на позицию. keep_first — «Практика»: разбор уже показан, первый ответ не заменяется. Иначе
// остаётся самый поздний по answered_at: очередь без сети может прийти не по порядку.
func (q *Queries) SaveTrainingAnswer(ctx context.Context, arg SaveTrainingAnswerParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveTrainingAnswer,
		arg.OptionIds,
		arg.DontKnow,
		arg.Flagged,
		arg.AnsweredAt,
		arg.ElapsedMs,
		arg.Correct,
		arg.TrainingID,
		arg.Position,
		arg.KeepFirst,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const trainingHasQuestion = `-- name: TrainingHasQuestion :one
SELECT EXISTS (SELECT 1 FROM training_items WHERE training_id = $1 AND question_id = $2)
`

type TrainingHasQuestionParams struct {
	TrainingID uuid.UUID
	QuestionID uuid.UUID
}

func (q *Queries) TrainingHasQuestion(ctx context.Context, arg TrainingHasQuestionParams) (bool, error) {
	row := q.db.QueryRow(ctx, trainingHasQuestion, arg.TrainingID, arg.QuestionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertQuestion = `-- name: UpsertQuestion :exec
INSERT INTO questions (id, question_type, topic_id, difficulty, status, body, answer, explanation)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET question_type = excluded.question_type, topic_id = excluded.topic_id,
  difficulty = excluded.difficulty, status = excluded.status, body = excluded.body, answer = excluded.answer,
  explanation = excluded.explanation, updated_at = now()
`

type UpsertQuestionParams struct {
	ID           uuid.UUID
	QuestionType string
	TopicID      string
	Difficulty   string
	Status       string
	Body         []byte
	Answer       []string
	Explanation  []byte
}

func (q *Queries) UpsertQuestion(ctx context.Context, arg UpsertQuestionParams) error {
	_, err := q.db.Exec(ctx, upsertQuestion,
		arg.ID,
		arg.QuestionType,
		arg.TopicID,
		arg.Difficulty,
		arg.Status,
		arg.Body,
		arg.Answer,
		arg.Explanation,
	)
	return err
}

const upsertTopic = `-- name: UpsertTopic :exec
INSERT INTO topics (id, section, title_ru, title_en, position) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET section = excluded.section, title_ru = excluded.title_ru,
  title_en = excluded.title_en, position = excluded.position
`

type UpsertTopicParams struct {
	ID       string
	Section  string
	TitleRu  string
	TitleEn  string
	Position int
}

// Набор для разработки (greprep seed-dev) и тестов; в бой контент приходит через админку.
func (q *Queries) UpsertTopic(ctx context.Context, arg UpsertTopicParams) error {
	_, err := q.db.Exec(ctx, upsertTopic,
		arg.ID,
		arg.Section,
		arg.TitleRu,
		arg.TitleEn,
		arg.Position,
	)
	return err
}
