// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/AuthorizationCodeSignIn
type AuthorizationCodeSignIn struct {
	Provider IdentityProvider `json:"provider"`
	Code     string           `json:"code"`
	// PKCE (RFC 7636).
	CodeVerifier string `json:"codeVerifier"`
	// Должен совпасть с одним из зарегистрированных у
	// провайдера.
	RedirectUri string           `json:"redirectUri"`
	Nonce       OptString        `json:"nonce"`
	Transport   SessionTransport `json:"transport"`
	ClientKind  OptClientKind    `json:"clientKind"`
}

// GetProvider returns the value of Provider.
func (s *AuthorizationCodeSignIn) GetProvider() IdentityProvider {
	return s.Provider
}

// GetCode returns the value of Code.
func (s *AuthorizationCodeSignIn) GetCode() string {
	return s.Code
}

// GetCodeVerifier returns the value of CodeVerifier.
func (s *AuthorizationCodeSignIn) GetCodeVerifier() string {
	return s.CodeVerifier
}

// GetRedirectUri returns the value of RedirectUri.
func (s *AuthorizationCodeSignIn) GetRedirectUri() string {
	return s.RedirectUri
}

// GetNonce returns the value of Nonce.
func (s *AuthorizationCodeSignIn) GetNonce() OptString {
	return s.Nonce
}

// GetTransport returns the value of Transport.
func (s *AuthorizationCodeSignIn) GetTransport() SessionTransport {
	return s.Transport
}

// GetClientKind returns the value of ClientKind.
func (s *AuthorizationCodeSignIn) GetClientKind() OptClientKind {
	return s.ClientKind
}

// SetProvider sets the value of Provider.
func (s *AuthorizationCodeSignIn) SetProvider(val IdentityProvider) {
	s.Provider = val
}

// SetCode sets the value of Code.
func (s *AuthorizationCodeSignIn) SetCode(val string) {
	s.Code = val
}

// SetCodeVerifier sets the value of CodeVerifier.
func (s *AuthorizationCodeSignIn) SetCodeVerifier(val string) {
	s.CodeVerifier = val
}

// SetRedirectUri sets the value of RedirectUri.
func (s *AuthorizationCodeSignIn) SetRedirectUri(val string) {
	s.RedirectUri = val
}

// SetNonce sets the value of Nonce.
func (s *AuthorizationCodeSignIn) SetNonce(val OptString) {
	s.Nonce = val
}

// SetTransport sets the value of Transport.
func (s *AuthorizationCodeSignIn) SetTransport(val SessionTransport) {
	s.Transport = val
}

// SetClientKind sets the value of ClientKind.
func (s *AuthorizationCodeSignIn) SetClientKind(val OptClientKind) {
	s.ClientKind = val
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/ClientError
type ClientError struct {
	Message string    `json:"message"`
	Stack   OptString `json:"stack"`
	// Экран или путь, без параметров с личными данными.
	Route OptString `json:"route"`
	// X-Request-Id запроса, после которого случилась ошибка, если
	// был.
	RequestId  OptString  `json:"requestId"`
	ClientKind ClientKind `json:"clientKind"`
	AppVersion string     `json:"appVersion"`
	OccurredAt time.Time  `json:"occurredAt"`
}

// GetMessage returns the value of Message.
func (s *ClientError) GetMessage() string {
	return s.Message
}

// GetStack returns the value of Stack.
func (s *ClientError) GetStack() OptString {
	return s.Stack
}

// GetRoute returns the value of Route.
func (s *ClientError) GetRoute() OptString {
	return s.Route
}

// GetRequestId returns the value of RequestId.
func (s *ClientError) GetRequestId() OptString {
	return s.RequestId
}

// GetClientKind returns the value of ClientKind.
func (s *ClientError) GetClientKind() ClientKind {
	return s.ClientKind
}

// GetAppVersion returns the value of AppVersion.
func (s *ClientError) GetAppVersion() string {
	return s.AppVersion
}

// GetOccurredAt returns the value of OccurredAt.
func (s *ClientError) GetOccurredAt() time.Time {
	return s.OccurredAt
}

// SetMessage sets the value of Message.
func (s *ClientError) SetMessage(val string) {
	s.Message = val
}

// SetStack sets the value of Stack.
func (s *ClientError) SetStack(val OptString) {
	s.Stack = val
}

// SetRoute sets the value of Route.
func (s *ClientError) SetRoute(val OptString) {
	s.Route = val
}

// SetRequestId sets the value of RequestId.
func (s *ClientError) SetRequestId(val OptString) {
	s.RequestId = val
}

// SetClientKind sets the value of ClientKind.
func (s *ClientError) SetClientKind(val ClientKind) {
	s.ClientKind = val
}

// SetAppVersion sets the value of AppVersion.
func (s *ClientError) SetAppVersion(val string) {
	s.AppVersion = val
}

// SetOccurredAt sets the value of OccurredAt.
func (s *ClientError) SetOccurredAt(val time.Time) {
	s.OccurredAt = val
}

// Ref: #/components/schemas/ClientKind
type ClientKind string

const (
	ClientKindWeb      ClientKind = "web"
	ClientKindTelegram ClientKind = "telegram"
	ClientKindIos      ClientKind = "ios"
	ClientKindMacos    ClientKind = "macos"
	ClientKindAndroid  ClientKind = "android"
	ClientKindAdmin    ClientKind = "admin"
)

// AllValues returns all ClientKind values.
func (ClientKind) AllValues() []ClientKind {
	return []ClientKind{
		ClientKindWeb,
		ClientKindTelegram,
		ClientKindIos,
		ClientKindMacos,
		ClientKindAndroid,
		ClientKindAdmin,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ClientKind) MarshalText() ([]byte, error) {
	switch s {
	case ClientKindWeb:
		return []byte(s), nil
	case ClientKindTelegram:
		return []byte(s), nil
	case ClientKindIos:
		return []byte(s), nil
	case ClientKindMacos:
		return []byte(s), nil
	case ClientKindAndroid:
		return []byte(s), nil
	case ClientKindAdmin:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ClientKind) UnmarshalText(data []byte) error {
	switch ClientKind(data) {
	case ClientKindWeb:
		*s = ClientKindWeb
		return nil
	case ClientKindTelegram:
		*s = ClientKindTelegram
		return nil
	case ClientKindIos:
		*s = ClientKindIos
		return nil
	case ClientKindMacos:
		*s = ClientKindMacos
		return nil
	case ClientKindAndroid:
		*s = ClientKindAndroid
		return nil
	case ClientKindAdmin:
		*s = ClientKindAdmin
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CookieAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *CookieAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *CookieAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *CookieAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *CookieAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/DevSignIn
type DevSignIn struct {
	// Имя тестового пользователя; один и тот же name — один и
	// тот же пользователь.
	Name       string           `json:"name"`
	Role       OptRole          `json:"role"`
	Transport  SessionTransport `json:"transport"`
	ClientKind OptClientKind    `json:"clientKind"`
}

// GetName returns the value of Name.
func (s *DevSignIn) GetName() string {
	return s.Name
}

// GetRole returns the value of Role.
func (s *DevSignIn) GetRole() OptRole {
	return s.Role
}

// GetTransport returns the value of Transport.
func (s *DevSignIn) GetTransport() SessionTransport {
	return s.Transport
}

// GetClientKind returns the value of ClientKind.
func (s *DevSignIn) GetClientKind() OptClientKind {
	return s.ClientKind
}

// SetName sets the value of Name.
func (s *DevSignIn) SetName(val string) {
	s.Name = val
}

// SetRole sets the value of Role.
func (s *DevSignIn) SetRole(val OptRole) {
	s.Role = val
}

// SetTransport sets the value of Transport.
func (s *DevSignIn) SetTransport(val SessionTransport) {
	s.Transport = val
}

// SetClientKind sets the value of ClientKind.
func (s *DevSignIn) SetClientKind(val OptClientKind) {
	s.ClientKind = val
}

// Ref: #/components/schemas/Error
type Error struct {
	// Машинный код: bad_request, unauthorized, forbidden, not_found, too_many_requests,
	// invalid_init_data, invalid_id_token, internal. Клиент показывает текст по
	// коду, а не message.
	Code string `json:"code"`
	// Для журнала и разработчика, не для экрана.
	Message   string `json:"message"`
	RequestId string `json:"requestId"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// GetRequestId returns the value of RequestId.
func (s *Error) GetRequestId() string {
	return s.RequestId
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// SetRequestId sets the value of RequestId.
func (s *Error) SetRequestId(val string) {
	s.RequestId = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/Health
type Health struct {
	Status HealthStatus `json:"status"`
	// Коммит сборки — сверка «в бою новое» после выкладки.
	Version string `json:"version"`
}

// GetStatus returns the value of Status.
func (s *Health) GetStatus() HealthStatus {
	return s.Status
}

// GetVersion returns the value of Version.
func (s *Health) GetVersion() string {
	return s.Version
}

// SetStatus sets the value of Status.
func (s *Health) SetStatus(val HealthStatus) {
	s.Status = val
}

// SetVersion sets the value of Version.
func (s *Health) SetVersion(val string) {
	s.Version = val
}

type HealthStatus string

const (
	HealthStatusOk HealthStatus = "ok"
)

// AllValues returns all HealthStatus values.
func (HealthStatus) AllValues() []HealthStatus {
	return []HealthStatus{
		HealthStatusOk,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthStatusOk:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthStatus) UnmarshalText(data []byte) error {
	switch HealthStatus(data) {
	case HealthStatusOk:
		*s = HealthStatusOk
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/IdTokenSignIn
type IdTokenSignIn struct {
	Provider IdentityProvider `json:"provider"`
	IdToken  string           `json:"idToken"`
	// Тот же nonce, что ушёл провайдеру; сервер сверяет его с
	// токеном.
	Nonce string `json:"nonce"`
	// Имя, которое Apple отдаёт приложению только при первом
	// входе (в id_token его нет). Берётся только для нового
	// аккаунта.
	DisplayName OptString        `json:"displayName"`
	Transport   SessionTransport `json:"transport"`
	ClientKind  OptClientKind    `json:"clientKind"`
}

// GetProvider returns the value of Provider.
func (s *IdTokenSignIn) GetProvider() IdentityProvider {
	return s.Provider
}

// GetIdToken returns the value of IdToken.
func (s *IdTokenSignIn) GetIdToken() string {
	return s.IdToken
}

// GetNonce returns the value of Nonce.
func (s *IdTokenSignIn) GetNonce() string {
	return s.Nonce
}

// GetDisplayName returns the value of DisplayName.
func (s *IdTokenSignIn) GetDisplayName() OptString {
	return s.DisplayName
}

// GetTransport returns the value of Transport.
func (s *IdTokenSignIn) GetTransport() SessionTransport {
	return s.Transport
}

// GetClientKind returns the value of ClientKind.
func (s *IdTokenSignIn) GetClientKind() OptClientKind {
	return s.ClientKind
}

// SetProvider sets the value of Provider.
func (s *IdTokenSignIn) SetProvider(val IdentityProvider) {
	s.Provider = val
}

// SetIdToken sets the value of IdToken.
func (s *IdTokenSignIn) SetIdToken(val string) {
	s.IdToken = val
}

// SetNonce sets the value of Nonce.
func (s *IdTokenSignIn) SetNonce(val string) {
	s.Nonce = val
}

// SetDisplayName sets the value of DisplayName.
func (s *IdTokenSignIn) SetDisplayName(val OptString) {
	s.DisplayName = val
}

// SetTransport sets the value of Transport.
func (s *IdTokenSignIn) SetTransport(val SessionTransport) {
	s.Transport = val
}

// SetClientKind sets the value of ClientKind.
func (s *IdTokenSignIn) SetClientKind(val OptClientKind) {
	s.ClientKind = val
}

// Ref: #/components/schemas/IdentityProvider
type IdentityProvider string

const (
	IdentityProviderTelegram IdentityProvider = "telegram"
	IdentityProviderApple    IdentityProvider = "apple"
	IdentityProviderGoogle   IdentityProvider = "google"
)

// AllValues returns all IdentityProvider values.
func (IdentityProvider) AllValues() []IdentityProvider {
	return []IdentityProvider{
		IdentityProviderTelegram,
		IdentityProviderApple,
		IdentityProviderGoogle,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s IdentityProvider) MarshalText() ([]byte, error) {
	switch s {
	case IdentityProviderTelegram:
		return []byte(s), nil
	case IdentityProviderApple:
		return []byte(s), nil
	case IdentityProviderGoogle:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *IdentityProvider) UnmarshalText(data []byte) error {
	switch IdentityProvider(data) {
	case IdentityProviderTelegram:
		*s = IdentityProviderTelegram
		return nil
	case IdentityProviderApple:
		*s = IdentityProviderApple
		return nil
	case IdentityProviderGoogle:
		*s = IdentityProviderGoogle
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/LinkedIdentity
type LinkedIdentity struct {
	Provider IdentityProvider `json:"provider"`
	LinkedAt time.Time        `json:"linkedAt"`
}

// GetProvider returns the value of Provider.
func (s *LinkedIdentity) GetProvider() IdentityProvider {
	return s.Provider
}

// GetLinkedAt returns the value of LinkedAt.
func (s *LinkedIdentity) GetLinkedAt() time.Time {
	return s.LinkedAt
}

// SetProvider sets the value of Provider.
func (s *LinkedIdentity) SetProvider(val IdentityProvider) {
	s.Provider = val
}

// SetLinkedAt sets the value of LinkedAt.
func (s *LinkedIdentity) SetLinkedAt(val time.Time) {
	s.LinkedAt = val
}

// Ref: #/components/schemas/Locale
type Locale string

const (
	LocaleRu Locale = "ru"
	LocaleEn Locale = "en"
)

// AllValues returns all Locale values.
func (Locale) AllValues() []Locale {
	return []Locale{
		LocaleRu,
		LocaleEn,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Locale) MarshalText() ([]byte, error) {
	switch s {
	case LocaleRu:
		return []byte(s), nil
	case LocaleEn:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Locale) UnmarshalText(data []byte) error {
	switch Locale(data) {
	case LocaleRu:
		*s = LocaleRu
		return nil
	case LocaleEn:
		*s = LocaleEn
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptClientKind returns new OptClientKind with value set to v.
func NewOptClientKind(v ClientKind) OptClientKind {
	return OptClientKind{
		Value: v,
		Set:   true,
	}
}

// OptClientKind is optional ClientKind.
type OptClientKind struct {
	Value ClientKind
	Set   bool
}

// IsSet returns true if OptClientKind was set.
func (o OptClientKind) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptClientKind) Reset() {
	var v ClientKind
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptClientKind) SetTo(v ClientKind) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptClientKind) Get() (v ClientKind, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptClientKind) Or(d ClientKind) ClientKind {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRole returns new OptRole with value set to v.
func NewOptRole(v Role) OptRole {
	return OptRole{
		Value: v,
		Set:   true,
	}
}

// OptRole is optional Role.
type OptRole struct {
	Value Role
	Set   bool
}

// IsSet returns true if OptRole was set.
func (o OptRole) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRole) Reset() {
	var v Role
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRole) SetTo(v Role) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRole) Get() (v Role, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRole) Or(d Role) Role {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// ReportClientErrorNoContent is response for ReportClientError operation.
type ReportClientErrorNoContent struct{}

// Ref: #/components/schemas/ReviewItem
type ReviewItem struct {
	ID    uuid.UUID      `json:"id"`
	Kind  ReviewItemKind `json:"kind"`
	Title string         `json:"title"`
}

// GetID returns the value of ID.
func (s *ReviewItem) GetID() uuid.UUID {
	return s.ID
}

// GetKind returns the value of Kind.
func (s *ReviewItem) GetKind() ReviewItemKind {
	return s.Kind
}

// GetTitle returns the value of Title.
func (s *ReviewItem) GetTitle() string {
	return s.Title
}

// SetID sets the value of ID.
func (s *ReviewItem) SetID(val uuid.UUID) {
	s.ID = val
}

// SetKind sets the value of Kind.
func (s *ReviewItem) SetKind(val ReviewItemKind) {
	s.Kind = val
}

// SetTitle sets the value of Title.
func (s *ReviewItem) SetTitle(val string) {
	s.Title = val
}

type ReviewItemKind string

const (
	ReviewItemKindQuestion    ReviewItemKind = "question"
	ReviewItemKindWord        ReviewItemKind = "word"
	ReviewItemKindTheory      ReviewItemKind = "theory"
	ReviewItemKindEssayPrompt ReviewItemKind = "essay_prompt"
)

// AllValues returns all ReviewItemKind values.
func (ReviewItemKind) AllValues() []ReviewItemKind {
	return []ReviewItemKind{
		ReviewItemKindQuestion,
		ReviewItemKindWord,
		ReviewItemKindTheory,
		ReviewItemKindEssayPrompt,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ReviewItemKind) MarshalText() ([]byte, error) {
	switch s {
	case ReviewItemKindQuestion:
		return []byte(s), nil
	case ReviewItemKindWord:
		return []byte(s), nil
	case ReviewItemKindTheory:
		return []byte(s), nil
	case ReviewItemKindEssayPrompt:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ReviewItemKind) UnmarshalText(data []byte) error {
	switch ReviewItemKind(data) {
	case ReviewItemKindQuestion:
		*s = ReviewItemKindQuestion
		return nil
	case ReviewItemKindWord:
		*s = ReviewItemKindWord
		return nil
	case ReviewItemKindTheory:
		*s = ReviewItemKindTheory
		return nil
	case ReviewItemKindEssayPrompt:
		*s = ReviewItemKindEssayPrompt
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ReviewQueue
type ReviewQueue struct {
	Items []ReviewItem `json:"items"`
}

// GetItems returns the value of Items.
func (s *ReviewQueue) GetItems() []ReviewItem {
	return s.Items
}

// SetItems sets the value of Items.
func (s *ReviewQueue) SetItems(val []ReviewItem) {
	s.Items = val
}

// Ref: #/components/schemas/Role
type Role string

const (
	RoleUser  Role = "user"
	RoleAdmin Role = "admin"
)

// AllValues returns all Role values.
func (Role) AllValues() []Role {
	return []Role{
		RoleUser,
		RoleAdmin,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Role) MarshalText() ([]byte, error) {
	switch s {
	case RoleUser:
		return []byte(s), nil
	case RoleAdmin:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Role) UnmarshalText(data []byte) error {
	switch Role(data) {
	case RoleUser:
		*s = RoleUser
		return nil
	case RoleAdmin:
		*s = RoleAdmin
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Section
type Section string

const (
	SectionVerbal Section = "verbal"
	SectionQuant  Section = "quant"
	SectionWords  Section = "words"
	SectionEssay  Section = "essay"
)

// AllValues returns all Section values.
func (Section) AllValues() []Section {
	return []Section{
		SectionVerbal,
		SectionQuant,
		SectionWords,
		SectionEssay,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Section) MarshalText() ([]byte, error) {
	switch s {
	case SectionVerbal:
		return []byte(s), nil
	case SectionQuant:
		return []byte(s), nil
	case SectionWords:
		return []byte(s), nil
	case SectionEssay:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Section) UnmarshalText(data []byte) error {
	switch Section(data) {
	case SectionVerbal:
		*s = SectionVerbal
		return nil
	case SectionQuant:
		*s = SectionQuant
		return nil
	case SectionWords:
		*s = SectionWords
		return nil
	case SectionEssay:
		*s = SectionEssay
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Session
type Session struct {
	// Только при transport=bearer; хранить в Keychain / Keystore, в мини-аппе
	// — в памяти.
	Token OptString `json:"token"`
	// Когда сессия истечёт без активности.
	ExpiresAt time.Time `json:"expiresAt"`
	User      User      `json:"user"`
}

// GetToken returns the value of Token.
func (s *Session) GetToken() OptString {
	return s.Token
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *Session) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// GetUser returns the value of User.
func (s *Session) GetUser() User {
	return s.User
}

// SetToken sets the value of Token.
func (s *Session) SetToken(val OptString) {
	s.Token = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *Session) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}

// SetUser sets the value of User.
func (s *Session) SetUser(val User) {
	s.User = val
}

// SessionHeaders wraps Session with response headers.
type SessionHeaders struct {
	SetCookie OptString
	Response  Session
}

// GetSetCookie returns the value of SetCookie.
func (s *SessionHeaders) GetSetCookie() OptString {
	return s.SetCookie
}

// GetResponse returns the value of Response.
func (s *SessionHeaders) GetResponse() Session {
	return s.Response
}

// SetSetCookie sets the value of SetCookie.
func (s *SessionHeaders) SetSetCookie(val OptString) {
	s.SetCookie = val
}

// SetResponse sets the value of Response.
func (s *SessionHeaders) SetResponse(val Session) {
	s.Response = val
}

// Bearer — токен в теле (мини-апп, приложения); cookie — токен
// только в куке __Host-session (сайт, админка), в теле его нет.
// Ref: #/components/schemas/SessionTransport
type SessionTransport string

const (
	SessionTransportBearer SessionTransport = "bearer"
	SessionTransportCookie SessionTransport = "cookie"
)

// AllValues returns all SessionTransport values.
func (SessionTransport) AllValues() []SessionTransport {
	return []SessionTransport{
		SessionTransportBearer,
		SessionTransportCookie,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SessionTransport) MarshalText() ([]byte, error) {
	switch s {
	case SessionTransportBearer:
		return []byte(s), nil
	case SessionTransportCookie:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SessionTransport) UnmarshalText(data []byte) error {
	switch SessionTransport(data) {
	case SessionTransportBearer:
		*s = SessionTransportBearer
		return nil
	case SessionTransportCookie:
		*s = SessionTransportCookie
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// SignOutNoContent is response for SignOut operation.
type SignOutNoContent struct {
	SetCookie OptString
}

// GetSetCookie returns the value of SetCookie.
func (s *SignOutNoContent) GetSetCookie() OptString {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *SignOutNoContent) SetSetCookie(val OptString) {
	s.SetCookie = val
}

// Ref: #/components/schemas/StepState
type StepState string

const (
	StepStateDone    StepState = "done"
	StepStateCurrent StepState = "current"
	StepStateNext    StepState = "next"
)

// AllValues returns all StepState values.
func (StepState) AllValues() []StepState {
	return []StepState{
		StepStateDone,
		StepStateCurrent,
		StepStateNext,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s StepState) MarshalText() ([]byte, error) {
	switch s {
	case StepStateDone:
		return []byte(s), nil
	case StepStateCurrent:
		return []byte(s), nil
	case StepStateNext:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *StepState) UnmarshalText(data []byte) error {
	switch StepState(data) {
	case StepStateDone:
		*s = StepStateDone
		return nil
	case StepStateCurrent:
		*s = StepStateCurrent
		return nil
	case StepStateNext:
		*s = StepStateNext
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/TelegramMiniAppSignIn
type TelegramMiniAppSignIn struct {
	// Сырая строка initData от Telegram.
	InitData string `json:"initData"`
}

// GetInitData returns the value of InitData.
func (s *TelegramMiniAppSignIn) GetInitData() string {
	return s.InitData
}

// SetInitData sets the value of InitData.
func (s *TelegramMiniAppSignIn) SetInitData(val string) {
	s.InitData = val
}

// Ref: #/components/schemas/Today
type Today struct {
	Date  time.Time   `json:"date"`
	Steps []TodayStep `json:"steps"`
}

// GetDate returns the value of Date.
func (s *Today) GetDate() time.Time {
	return s.Date
}

// GetSteps returns the value of Steps.
func (s *Today) GetSteps() []TodayStep {
	return s.Steps
}

// SetDate sets the value of Date.
func (s *Today) SetDate(val time.Time) {
	s.Date = val
}

// SetSteps sets the value of Steps.
func (s *Today) SetSteps(val []TodayStep) {
	s.Steps = val
}

// Ref: #/components/schemas/TodayStep
type TodayStep struct {
	ID      string  `json:"id"`
	Section Section `json:"section"`
	// На языке интерфейса человека.
	Title   string    `json:"title"`
	Minutes int       `json:"minutes"`
	State   StepState `json:"state"`
}

// GetID returns the value of ID.
func (s *TodayStep) GetID() string {
	return s.ID
}

// GetSection returns the value of Section.
func (s *TodayStep) GetSection() Section {
	return s.Section
}

// GetTitle returns the value of Title.
func (s *TodayStep) GetTitle() string {
	return s.Title
}

// GetMinutes returns the value of Minutes.
func (s *TodayStep) GetMinutes() int {
	return s.Minutes
}

// GetState returns the value of State.
func (s *TodayStep) GetState() StepState {
	return s.State
}

// SetID sets the value of ID.
func (s *TodayStep) SetID(val string) {
	s.ID = val
}

// SetSection sets the value of Section.
func (s *TodayStep) SetSection(val Section) {
	s.Section = val
}

// SetTitle sets the value of Title.
func (s *TodayStep) SetTitle(val string) {
	s.Title = val
}

// SetMinutes sets the value of Minutes.
func (s *TodayStep) SetMinutes(val int) {
	s.Minutes = val
}

// SetState sets the value of State.
func (s *TodayStep) SetState(val StepState) {
	s.State = val
}

// Ref: #/components/schemas/User
type User struct {
	ID         uuid.UUID        `json:"id"`
	Name       string           `json:"name"`
	Role       Role             `json:"role"`
	Locale     Locale           `json:"locale"`
	Identities []LinkedIdentity `json:"identities"`
}

// GetID returns the value of ID.
func (s *User) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *User) GetName() string {
	return s.Name
}

// GetRole returns the value of Role.
func (s *User) GetRole() Role {
	return s.Role
}

// GetLocale returns the value of Locale.
func (s *User) GetLocale() Locale {
	return s.Locale
}

// GetIdentities returns the value of Identities.
func (s *User) GetIdentities() []LinkedIdentity {
	return s.Identities
}

// SetID sets the value of ID.
func (s *User) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *User) SetName(val string) {
	s.Name = val
}

// SetRole sets the value of Role.
func (s *User) SetRole(val Role) {
	s.Role = val
}

// SetLocale sets the value of Locale.
func (s *User) SetLocale(val Locale) {
	s.Locale = val
}

// SetIdentities sets the value of Identities.
func (s *User) SetIdentities(val []LinkedIdentity) {
	s.Identities = val
}
