// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// FinishTraining implements finishTraining operation.
	//
	// Повторный вызов возвращает тот же итог.
	//
	// POST /api/trainings/{trainingId}/finish
	FinishTraining(ctx context.Context, req *TrainingFinish, params FinishTrainingParams) (*TrainingSummary, error)
	// GetHealth implements getHealth operation.
	//
	// Жив ли сервер и какая сборка (сверка после выкладки).
	//
	// GET /api/health
	GetHealth(ctx context.Context) (*Health, error)
	// GetMe implements getMe operation.
	//
	// Кто вошёл.
	//
	// GET /api/me
	GetMe(ctx context.Context) (*User, error)
	// GetReviewQueue implements getReviewQueue operation.
	//
	// Только роль admin; остальным — 403 forbidden.
	//
	// GET /api/admin/review-queue
	GetReviewQueue(ctx context.Context) (*ReviewQueue, error)
	// GetToday implements getToday operation.
	//
	// Лента шагов на сегодня (экран «Сегодня»).
	//
	// GET /api/today
	GetToday(ctx context.Context) (*Today, error)
	// GetTraining implements getTraining operation.
	//
	// Чужая или несуществующая — 404 not_found, не 403, чтобы id чужих
	// сессий не подтверждались.
	//
	// GET /api/trainings/{trainingId}
	GetTraining(ctx context.Context, params GetTrainingParams) (*TrainingSession, error)
	// GetTrainingOptions implements getTrainingOptions operation.
	//
	// Типы заданий с темами и числом доступных заданий
	// (пустую выборку не собрать), готовые наборы и прошлая
	// тренировка — чтобы «Начать» было видно сразу. Только
	// проверенные задания.
	//
	// GET /api/trainings/options
	GetTrainingOptions(ctx context.Context, params GetTrainingOptionsParams) (*TrainingOptions, error)
	// ReportClientError implements reportClientError operation.
	//
	// Можно без входа (ошибка до входа тоже важна). Размер
	// тела и частота ограничены на сервере.
	//
	// POST /api/client-errors
	ReportClientError(ctx context.Context, req *ClientError) error
	// ReportQuestion implements reportQuestion operation.
	//
	// «Сообщить об ошибке» в задании — в очередь админки.
	//
	// POST /api/questions/{questionId}/reports
	ReportQuestion(ctx context.Context, req *QuestionReport, params ReportQuestionParams) error
	// SignInForDevelopment implements signInForDevelopment operation.
	//
	// Включается переменной DEV_AUTH=1, которую сервер
	// отказывается принять вместе с APP_ENV=production (проверено
	// тестом). Тем же путём e2e заводит своего пользователя на
	// каждый тест.
	//
	// POST /api/auth/dev
	SignInForDevelopment(ctx context.Context, req *DevSignIn) (*SessionHeaders, error)
	// SignInWithAuthorizationCode implements signInWithAuthorizationCode operation.
	//
	// Код обменивается на id_token на сервере: для обмена нужен
	// секрет клиента, на устройство он не попадает. PKCE —
	// обязательно.
	//
	// POST /api/auth/oidc/code
	SignInWithAuthorizationCode(ctx context.Context, req *AuthorizationCodeSignIn) (*SessionHeaders, error)
	// SignInWithIdToken implements signInWithIdToken operation.
	//
	// Родная кнопка Apple и Credential Manager Google отдают id_token прямо на
	// устройстве. Сервер проверяет подпись по ключам
	// компании, издателя, получателя, срок и nonce.
	//
	// POST /api/auth/oidc
	SignInWithIdToken(ctx context.Context, req *IdTokenSignIn) (*SessionHeaders, error)
	// SignInWithTelegramMiniApp implements signInWithTelegramMiniApp operation.
	//
	// Вход из мини-аппа по initData (подпись проверяется ключом
	// бота).
	//
	// POST /api/auth/telegram-mini-app
	SignInWithTelegramMiniApp(ctx context.Context, req *TelegramMiniAppSignIn) (*Session, error)
	// SignOut implements signOut operation.
	//
	// Выйти на этом устройстве — сессия удаляется сразу.
	//
	// POST /api/auth/logout
	SignOut(ctx context.Context) (*SignOutNoContent, error)
	// StartTraining implements startTraining operation.
	//
	// Всё нужное для сессии приходит одним ответом, чтобы
	// начатая тренировка дожила без сети (PRODUCT.md, «Operating
	// Context»). Задания — только проверенные, сначала те, что
	// человек ещё не решал. Нет ни одного подходящего — 409
	// no_questions. Нет доступа к тренировкам — 403 forbidden.
	//
	// POST /api/trainings
	StartTraining(ctx context.Context, req *TrainingRequest) (*TrainingSession, error)
	// SubmitTrainingAnswers implements submitTrainingAnswers operation.
	//
	// Повторная отправка безопасна: ответ на позицию
	// заменяется, а не дублируется. В «Практике» остаётся
	// первый ответ (разбор уже показан), в «Проверке» — самый
	// поздний по answeredAt (очередь без сети может прийти не по
	// порядку). Сервер сам проверяет ответ по ключу —
	// клиенту для статистики не верит. После завершения
	// сессии ответы не принимаются (409 training_finished).
	//
	// POST /api/trainings/{trainingId}/answers
	SubmitTrainingAnswers(ctx context.Context, req *AnswerBatch, params SubmitTrainingAnswersParams) error
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
