// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetHealth implements getHealth operation.
//
// Жив ли сервер и какая сборка (сверка после выкладки).
//
// GET /api/health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *Health, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMe implements getMe operation.
//
// Кто вошёл.
//
// GET /api/me
func (UnimplementedHandler) GetMe(ctx context.Context) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// GetReviewQueue implements getReviewQueue operation.
//
// Только роль admin; остальным — 403 forbidden.
//
// GET /api/admin/review-queue
func (UnimplementedHandler) GetReviewQueue(ctx context.Context) (r *ReviewQueue, _ error) {
	return r, ht.ErrNotImplemented
}

// GetToday implements getToday operation.
//
// Лента шагов на сегодня (экран «Сегодня»).
//
// GET /api/today
func (UnimplementedHandler) GetToday(ctx context.Context) (r *Today, _ error) {
	return r, ht.ErrNotImplemented
}

// ReportClientError implements reportClientError operation.
//
// Можно без входа (ошибка до входа тоже важна). Размер
// тела и частота ограничены на сервере.
//
// POST /api/client-errors
func (UnimplementedHandler) ReportClientError(ctx context.Context, req *ClientError) error {
	return ht.ErrNotImplemented
}

// SignInForDevelopment implements signInForDevelopment operation.
//
// Включается переменной DEV_AUTH=1, которую сервер
// отказывается принять вместе с APP_ENV=production (проверено
// тестом). Тем же путём e2e заводит своего пользователя на
// каждый тест.
//
// POST /api/auth/dev
func (UnimplementedHandler) SignInForDevelopment(ctx context.Context, req *DevSignIn) (r *SessionHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// SignInWithAuthorizationCode implements signInWithAuthorizationCode operation.
//
// Код обменивается на id_token на сервере: для обмена нужен
// секрет клиента, на устройство он не попадает. PKCE —
// обязательно.
//
// POST /api/auth/oidc/code
func (UnimplementedHandler) SignInWithAuthorizationCode(ctx context.Context, req *AuthorizationCodeSignIn) (r *SessionHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// SignInWithIdToken implements signInWithIdToken operation.
//
// Родная кнопка Apple и Credential Manager Google отдают id_token прямо на
// устройстве. Сервер проверяет подпись по ключам
// компании, издателя, получателя, срок и nonce.
//
// POST /api/auth/oidc
func (UnimplementedHandler) SignInWithIdToken(ctx context.Context, req *IdTokenSignIn) (r *SessionHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// SignInWithTelegramMiniApp implements signInWithTelegramMiniApp operation.
//
// Вход из мини-аппа по initData (подпись проверяется ключом
// бота).
//
// POST /api/auth/telegram-mini-app
func (UnimplementedHandler) SignInWithTelegramMiniApp(ctx context.Context, req *TelegramMiniAppSignIn) (r *Session, _ error) {
	return r, ht.ErrNotImplemented
}

// SignOut implements signOut operation.
//
// Выйти на этом устройстве — сессия удаляется сразу.
//
// POST /api/auth/logout
func (UnimplementedHandler) SignOut(ctx context.Context) (r *SignOutNoContent, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
