// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Новый аккаунт без экзамена; выбор общий для всех
// устройств.
// Ref: #/components/schemas/ActiveExam
type ActiveExam string

const (
	ActiveExamGre   ActiveExam = "gre"
	ActiveExamToefl ActiveExam = "toefl"
)

// AllValues returns all ActiveExam values.
func (ActiveExam) AllValues() []ActiveExam {
	return []ActiveExam{
		ActiveExamGre,
		ActiveExamToefl,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ActiveExam) MarshalText() ([]byte, error) {
	switch s {
	case ActiveExamGre:
		return []byte(s), nil
	case ActiveExamToefl:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ActiveExam) UnmarshalText(data []byte) error {
	switch ActiveExam(data) {
	case ActiveExamGre:
		*s = ActiveExamGre
		return nil
	case ActiveExamToefl:
		*s = ActiveExamToefl
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/AnswerBatch
type AnswerBatch struct {
	Answers []GivenAnswer `json:"answers"`
}

// GetAnswers returns the value of Answers.
func (s *AnswerBatch) GetAnswers() []GivenAnswer {
	return s.Answers
}

// SetAnswers sets the value of Answers.
func (s *AnswerBatch) SetAnswers(val []GivenAnswer) {
	s.Answers = val
}

// Ref: #/components/schemas/AuthorizationCodeSignIn
type AuthorizationCodeSignIn struct {
	Provider IdentityProvider `json:"provider"`
	Code     string           `json:"code"`
	// PKCE (RFC 7636).
	CodeVerifier string `json:"codeVerifier"`
	// Должен совпасть с одним из зарегистрированных у
	// провайдера.
	RedirectUri string           `json:"redirectUri"`
	Nonce       OptString        `json:"nonce"`
	Transport   SessionTransport `json:"transport"`
	ClientKind  OptClientKind    `json:"clientKind"`
	// Язык интерфейса на устройстве. Берётся только для
	// нового аккаунта: у существующего вход язык не меняет.
	// Нет поля — русский.
	Locale OptLocale `json:"locale"`
}

// GetProvider returns the value of Provider.
func (s *AuthorizationCodeSignIn) GetProvider() IdentityProvider {
	return s.Provider
}

// GetCode returns the value of Code.
func (s *AuthorizationCodeSignIn) GetCode() string {
	return s.Code
}

// GetCodeVerifier returns the value of CodeVerifier.
func (s *AuthorizationCodeSignIn) GetCodeVerifier() string {
	return s.CodeVerifier
}

// GetRedirectUri returns the value of RedirectUri.
func (s *AuthorizationCodeSignIn) GetRedirectUri() string {
	return s.RedirectUri
}

// GetNonce returns the value of Nonce.
func (s *AuthorizationCodeSignIn) GetNonce() OptString {
	return s.Nonce
}

// GetTransport returns the value of Transport.
func (s *AuthorizationCodeSignIn) GetTransport() SessionTransport {
	return s.Transport
}

// GetClientKind returns the value of ClientKind.
func (s *AuthorizationCodeSignIn) GetClientKind() OptClientKind {
	return s.ClientKind
}

// GetLocale returns the value of Locale.
func (s *AuthorizationCodeSignIn) GetLocale() OptLocale {
	return s.Locale
}

// SetProvider sets the value of Provider.
func (s *AuthorizationCodeSignIn) SetProvider(val IdentityProvider) {
	s.Provider = val
}

// SetCode sets the value of Code.
func (s *AuthorizationCodeSignIn) SetCode(val string) {
	s.Code = val
}

// SetCodeVerifier sets the value of CodeVerifier.
func (s *AuthorizationCodeSignIn) SetCodeVerifier(val string) {
	s.CodeVerifier = val
}

// SetRedirectUri sets the value of RedirectUri.
func (s *AuthorizationCodeSignIn) SetRedirectUri(val string) {
	s.RedirectUri = val
}

// SetNonce sets the value of Nonce.
func (s *AuthorizationCodeSignIn) SetNonce(val OptString) {
	s.Nonce = val
}

// SetTransport sets the value of Transport.
func (s *AuthorizationCodeSignIn) SetTransport(val SessionTransport) {
	s.Transport = val
}

// SetClientKind sets the value of ClientKind.
func (s *AuthorizationCodeSignIn) SetClientKind(val OptClientKind) {
	s.ClientKind = val
}

// SetLocale sets the value of Locale.
func (s *AuthorizationCodeSignIn) SetLocale(val OptLocale) {
	s.Locale = val
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/ClientError
type ClientError struct {
	Message string    `json:"message"`
	Stack   OptString `json:"stack"`
	// Экран или путь, без параметров с личными данными.
	Route OptString `json:"route"`
	// X-Request-Id запроса, после которого случилась ошибка, если
	// был.
	RequestId  OptString  `json:"requestId"`
	ClientKind ClientKind `json:"clientKind"`
	AppVersion string     `json:"appVersion"`
	OccurredAt time.Time  `json:"occurredAt"`
}

// GetMessage returns the value of Message.
func (s *ClientError) GetMessage() string {
	return s.Message
}

// GetStack returns the value of Stack.
func (s *ClientError) GetStack() OptString {
	return s.Stack
}

// GetRoute returns the value of Route.
func (s *ClientError) GetRoute() OptString {
	return s.Route
}

// GetRequestId returns the value of RequestId.
func (s *ClientError) GetRequestId() OptString {
	return s.RequestId
}

// GetClientKind returns the value of ClientKind.
func (s *ClientError) GetClientKind() ClientKind {
	return s.ClientKind
}

// GetAppVersion returns the value of AppVersion.
func (s *ClientError) GetAppVersion() string {
	return s.AppVersion
}

// GetOccurredAt returns the value of OccurredAt.
func (s *ClientError) GetOccurredAt() time.Time {
	return s.OccurredAt
}

// SetMessage sets the value of Message.
func (s *ClientError) SetMessage(val string) {
	s.Message = val
}

// SetStack sets the value of Stack.
func (s *ClientError) SetStack(val OptString) {
	s.Stack = val
}

// SetRoute sets the value of Route.
func (s *ClientError) SetRoute(val OptString) {
	s.Route = val
}

// SetRequestId sets the value of RequestId.
func (s *ClientError) SetRequestId(val OptString) {
	s.RequestId = val
}

// SetClientKind sets the value of ClientKind.
func (s *ClientError) SetClientKind(val ClientKind) {
	s.ClientKind = val
}

// SetAppVersion sets the value of AppVersion.
func (s *ClientError) SetAppVersion(val string) {
	s.AppVersion = val
}

// SetOccurredAt sets the value of OccurredAt.
func (s *ClientError) SetOccurredAt(val time.Time) {
	s.OccurredAt = val
}

// Ref: #/components/schemas/ClientKind
type ClientKind string

const (
	ClientKindWeb      ClientKind = "web"
	ClientKindTelegram ClientKind = "telegram"
	ClientKindIos      ClientKind = "ios"
	ClientKindMacos    ClientKind = "macos"
	ClientKindAndroid  ClientKind = "android"
	ClientKindAdmin    ClientKind = "admin"
)

// AllValues returns all ClientKind values.
func (ClientKind) AllValues() []ClientKind {
	return []ClientKind{
		ClientKindWeb,
		ClientKindTelegram,
		ClientKindIos,
		ClientKindMacos,
		ClientKindAndroid,
		ClientKindAdmin,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ClientKind) MarshalText() ([]byte, error) {
	switch s {
	case ClientKindWeb:
		return []byte(s), nil
	case ClientKindTelegram:
		return []byte(s), nil
	case ClientKindIos:
		return []byte(s), nil
	case ClientKindMacos:
		return []byte(s), nil
	case ClientKindAndroid:
		return []byte(s), nil
	case ClientKindAdmin:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ClientKind) UnmarshalText(data []byte) error {
	switch ClientKind(data) {
	case ClientKindWeb:
		*s = ClientKindWeb
		return nil
	case ClientKindTelegram:
		*s = ClientKindTelegram
		return nil
	case ClientKindIos:
		*s = ClientKindIos
		return nil
	case ClientKindMacos:
		*s = ClientKindMacos
		return nil
	case ClientKindAndroid:
		*s = ClientKindAndroid
		return nil
	case ClientKindAdmin:
		*s = ClientKindAdmin
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CookieAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *CookieAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *CookieAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *CookieAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *CookieAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/DevSignIn
type DevSignIn struct {
	// Имя тестового пользователя; один и тот же name — один и
	// тот же пользователь.
	Name       string           `json:"name"`
	Role       OptRole          `json:"role"`
	Transport  SessionTransport `json:"transport"`
	ClientKind OptClientKind    `json:"clientKind"`
	// Язык интерфейса на устройстве. Берётся только для
	// нового аккаунта: у существующего вход язык не меняет.
	// Нет поля — русский.
	Locale OptLocale `json:"locale"`
}

// GetName returns the value of Name.
func (s *DevSignIn) GetName() string {
	return s.Name
}

// GetRole returns the value of Role.
func (s *DevSignIn) GetRole() OptRole {
	return s.Role
}

// GetTransport returns the value of Transport.
func (s *DevSignIn) GetTransport() SessionTransport {
	return s.Transport
}

// GetClientKind returns the value of ClientKind.
func (s *DevSignIn) GetClientKind() OptClientKind {
	return s.ClientKind
}

// GetLocale returns the value of Locale.
func (s *DevSignIn) GetLocale() OptLocale {
	return s.Locale
}

// SetName sets the value of Name.
func (s *DevSignIn) SetName(val string) {
	s.Name = val
}

// SetRole sets the value of Role.
func (s *DevSignIn) SetRole(val OptRole) {
	s.Role = val
}

// SetTransport sets the value of Transport.
func (s *DevSignIn) SetTransport(val SessionTransport) {
	s.Transport = val
}

// SetClientKind sets the value of ClientKind.
func (s *DevSignIn) SetClientKind(val OptClientKind) {
	s.ClientKind = val
}

// SetLocale sets the value of Locale.
func (s *DevSignIn) SetLocale(val OptLocale) {
	s.Locale = val
}

// Ref: #/components/schemas/Difficulty
type Difficulty string

const (
	DifficultyEasy   Difficulty = "easy"
	DifficultyMedium Difficulty = "medium"
	DifficultyHard   Difficulty = "hard"
)

// AllValues returns all Difficulty values.
func (Difficulty) AllValues() []Difficulty {
	return []Difficulty{
		DifficultyEasy,
		DifficultyMedium,
		DifficultyHard,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Difficulty) MarshalText() ([]byte, error) {
	switch s {
	case DifficultyEasy:
		return []byte(s), nil
	case DifficultyMedium:
		return []byte(s), nil
	case DifficultyHard:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Difficulty) UnmarshalText(data []byte) error {
	switch Difficulty(data) {
	case DifficultyEasy:
		*s = DifficultyEasy
		return nil
	case DifficultyMedium:
		*s = DifficultyMedium
		return nil
	case DifficultyHard:
		*s = DifficultyHard
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Сколько проверенных заданий каждой сложности.
// Ref: #/components/schemas/DifficultyCounts
type DifficultyCounts struct {
	Easy   int `json:"easy"`
	Medium int `json:"medium"`
	Hard   int `json:"hard"`
}

// GetEasy returns the value of Easy.
func (s *DifficultyCounts) GetEasy() int {
	return s.Easy
}

// GetMedium returns the value of Medium.
func (s *DifficultyCounts) GetMedium() int {
	return s.Medium
}

// GetHard returns the value of Hard.
func (s *DifficultyCounts) GetHard() int {
	return s.Hard
}

// SetEasy sets the value of Easy.
func (s *DifficultyCounts) SetEasy(val int) {
	s.Easy = val
}

// SetMedium sets the value of Medium.
func (s *DifficultyCounts) SetMedium(val int) {
	s.Medium = val
}

// SetHard sets the value of Hard.
func (s *DifficultyCounts) SetHard(val int) {
	s.Hard = val
}

// Ref: #/components/schemas/Error
type Error struct {
	// Машинный код: bad_request, unauthorized, forbidden, not_found, too_many_requests,
	// invalid_init_data, invalid_id_token, no_questions, training_finished, internal. Клиент
	// показывает текст по коду, а не message.
	Code string `json:"code"`
	// Для журнала и разработчика, не для экрана.
	Message   string `json:"message"`
	RequestId string `json:"requestId"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// GetRequestId returns the value of RequestId.
func (s *Error) GetRequestId() string {
	return s.RequestId
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// SetRequestId sets the value of RequestId.
func (s *Error) SetRequestId(val string) {
	s.RequestId = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/Exam
type Exam string

const (
	ExamGre   Exam = "gre"
	ExamToefl Exam = "toefl"
)

// AllValues returns all Exam values.
func (Exam) AllValues() []Exam {
	return []Exam{
		ExamGre,
		ExamToefl,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Exam) MarshalText() ([]byte, error) {
	switch s {
	case ExamGre:
		return []byte(s), nil
	case ExamToefl:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Exam) UnmarshalText(data []byte) error {
	switch Exam(data) {
	case ExamGre:
		*s = ExamGre
		return nil
	case ExamToefl:
		*s = ExamToefl
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ExamChoice
type ExamChoice struct {
	Exam Exam `json:"exam"`
}

// GetExam returns the value of Exam.
func (s *ExamChoice) GetExam() Exam {
	return s.Exam
}

// SetExam sets the value of Exam.
func (s *ExamChoice) SetExam(val Exam) {
	s.Exam = val
}

// Ref: #/components/schemas/ExamInfo
type ExamInfo struct {
	ID       Exam      `json:"id"`
	Sections []Section `json:"sections"`
}

// GetID returns the value of ID.
func (s *ExamInfo) GetID() Exam {
	return s.ID
}

// GetSections returns the value of Sections.
func (s *ExamInfo) GetSections() []Section {
	return s.Sections
}

// SetID sets the value of ID.
func (s *ExamInfo) SetID(val Exam) {
	s.ID = val
}

// SetSections sets the value of Sections.
func (s *ExamInfo) SetSections(val []Section) {
	s.Sections = val
}

// Ref: #/components/schemas/ExamList
type ExamList struct {
	Exams []ExamInfo `json:"exams"`
}

// GetExams returns the value of Exams.
func (s *ExamList) GetExams() []ExamInfo {
	return s.Exams
}

// SetExams sets the value of Exams.
func (s *ExamList) SetExams(val []ExamInfo) {
	s.Exams = val
}

// Разбор пишется заранее (PRODUCT.md, «Разбор ошибок»): почему
// верен ключ и почему соблазняет и не подходит каждый
// неверный вариант. Текст простой; слово — выделение
// (английские слова в русском тексте).
// Ref: #/components/schemas/Explanation
type Explanation struct {
	// Почему верен ключ — под «Верно / Неверно. Верный ответ
	// — A» (макеты R4, R6).
	Solution LocalizedText `json:"solution"`
	// «Почему не …?» — по неверным вариантам.
	Options []OptionExplanation `json:"options"`
}

// GetSolution returns the value of Solution.
func (s *Explanation) GetSolution() LocalizedText {
	return s.Solution
}

// GetOptions returns the value of Options.
func (s *Explanation) GetOptions() []OptionExplanation {
	return s.Options
}

// SetSolution sets the value of Solution.
func (s *Explanation) SetSolution(val LocalizedText) {
	s.Solution = val
}

// SetOptions sets the value of Options.
func (s *Explanation) SetOptions(val []OptionExplanation) {
	s.Options = val
}

// Ref: #/components/schemas/GivenAnswer
type GivenAnswer struct {
	Position int `json:"position"`
	// Пусто — не ответил (пропустил или «Не знаю»).
	OptionIds []string `json:"optionIds"`
	// «Не знаю» в «Практике» — для «что повторить» это
	// ошибка; только с пустым optionIds.
	DontKnow bool `json:"dontKnow"`
	// Отметка «вернуться» в «Проверке».
	Flagged    bool      `json:"flagged"`
	AnsweredAt time.Time `json:"answeredAt"`
	ElapsedMs  int       `json:"elapsedMs"`
}

// GetPosition returns the value of Position.
func (s *GivenAnswer) GetPosition() int {
	return s.Position
}

// GetOptionIds returns the value of OptionIds.
func (s *GivenAnswer) GetOptionIds() []string {
	return s.OptionIds
}

// GetDontKnow returns the value of DontKnow.
func (s *GivenAnswer) GetDontKnow() bool {
	return s.DontKnow
}

// GetFlagged returns the value of Flagged.
func (s *GivenAnswer) GetFlagged() bool {
	return s.Flagged
}

// GetAnsweredAt returns the value of AnsweredAt.
func (s *GivenAnswer) GetAnsweredAt() time.Time {
	return s.AnsweredAt
}

// GetElapsedMs returns the value of ElapsedMs.
func (s *GivenAnswer) GetElapsedMs() int {
	return s.ElapsedMs
}

// SetPosition sets the value of Position.
func (s *GivenAnswer) SetPosition(val int) {
	s.Position = val
}

// SetOptionIds sets the value of OptionIds.
func (s *GivenAnswer) SetOptionIds(val []string) {
	s.OptionIds = val
}

// SetDontKnow sets the value of DontKnow.
func (s *GivenAnswer) SetDontKnow(val bool) {
	s.DontKnow = val
}

// SetFlagged sets the value of Flagged.
func (s *GivenAnswer) SetFlagged(val bool) {
	s.Flagged = val
}

// SetAnsweredAt sets the value of AnsweredAt.
func (s *GivenAnswer) SetAnsweredAt(val time.Time) {
	s.AnsweredAt = val
}

// SetElapsedMs sets the value of ElapsedMs.
func (s *GivenAnswer) SetElapsedMs(val int) {
	s.ElapsedMs = val
}

// Ref: #/components/schemas/Health
type Health struct {
	Status HealthStatus `json:"status"`
	// Коммит сборки — сверка «в бою новое» после выкладки.
	Version string `json:"version"`
}

// GetStatus returns the value of Status.
func (s *Health) GetStatus() HealthStatus {
	return s.Status
}

// GetVersion returns the value of Version.
func (s *Health) GetVersion() string {
	return s.Version
}

// SetStatus sets the value of Status.
func (s *Health) SetStatus(val HealthStatus) {
	s.Status = val
}

// SetVersion sets the value of Version.
func (s *Health) SetVersion(val string) {
	s.Version = val
}

type HealthStatus string

const (
	HealthStatusOk HealthStatus = "ok"
)

// AllValues returns all HealthStatus values.
func (HealthStatus) AllValues() []HealthStatus {
	return []HealthStatus{
		HealthStatusOk,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthStatusOk:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthStatus) UnmarshalText(data []byte) error {
	switch HealthStatus(data) {
	case HealthStatusOk:
		*s = HealthStatusOk
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/IdTokenSignIn
type IdTokenSignIn struct {
	Provider IdentityProvider `json:"provider"`
	IdToken  string           `json:"idToken"`
	// Тот же nonce, что ушёл провайдеру; сервер сверяет его с
	// токеном.
	Nonce string `json:"nonce"`
	// Имя, которое Apple отдаёт приложению только при первом
	// входе (в id_token его нет). Берётся только для нового
	// аккаунта.
	DisplayName OptString        `json:"displayName"`
	Transport   SessionTransport `json:"transport"`
	ClientKind  OptClientKind    `json:"clientKind"`
	// Язык интерфейса на устройстве. Берётся только для
	// нового аккаунта: у существующего вход язык не меняет.
	// Нет поля — русский.
	Locale OptLocale `json:"locale"`
}

// GetProvider returns the value of Provider.
func (s *IdTokenSignIn) GetProvider() IdentityProvider {
	return s.Provider
}

// GetIdToken returns the value of IdToken.
func (s *IdTokenSignIn) GetIdToken() string {
	return s.IdToken
}

// GetNonce returns the value of Nonce.
func (s *IdTokenSignIn) GetNonce() string {
	return s.Nonce
}

// GetDisplayName returns the value of DisplayName.
func (s *IdTokenSignIn) GetDisplayName() OptString {
	return s.DisplayName
}

// GetTransport returns the value of Transport.
func (s *IdTokenSignIn) GetTransport() SessionTransport {
	return s.Transport
}

// GetClientKind returns the value of ClientKind.
func (s *IdTokenSignIn) GetClientKind() OptClientKind {
	return s.ClientKind
}

// GetLocale returns the value of Locale.
func (s *IdTokenSignIn) GetLocale() OptLocale {
	return s.Locale
}

// SetProvider sets the value of Provider.
func (s *IdTokenSignIn) SetProvider(val IdentityProvider) {
	s.Provider = val
}

// SetIdToken sets the value of IdToken.
func (s *IdTokenSignIn) SetIdToken(val string) {
	s.IdToken = val
}

// SetNonce sets the value of Nonce.
func (s *IdTokenSignIn) SetNonce(val string) {
	s.Nonce = val
}

// SetDisplayName sets the value of DisplayName.
func (s *IdTokenSignIn) SetDisplayName(val OptString) {
	s.DisplayName = val
}

// SetTransport sets the value of Transport.
func (s *IdTokenSignIn) SetTransport(val SessionTransport) {
	s.Transport = val
}

// SetClientKind sets the value of ClientKind.
func (s *IdTokenSignIn) SetClientKind(val OptClientKind) {
	s.ClientKind = val
}

// SetLocale sets the value of Locale.
func (s *IdTokenSignIn) SetLocale(val OptLocale) {
	s.Locale = val
}

// Ref: #/components/schemas/IdentityProvider
type IdentityProvider string

const (
	IdentityProviderTelegram IdentityProvider = "telegram"
	IdentityProviderApple    IdentityProvider = "apple"
	IdentityProviderGoogle   IdentityProvider = "google"
)

// AllValues returns all IdentityProvider values.
func (IdentityProvider) AllValues() []IdentityProvider {
	return []IdentityProvider{
		IdentityProviderTelegram,
		IdentityProviderApple,
		IdentityProviderGoogle,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s IdentityProvider) MarshalText() ([]byte, error) {
	switch s {
	case IdentityProviderTelegram:
		return []byte(s), nil
	case IdentityProviderApple:
		return []byte(s), nil
	case IdentityProviderGoogle:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *IdentityProvider) UnmarshalText(data []byte) error {
	switch IdentityProvider(data) {
	case IdentityProviderTelegram:
		*s = IdentityProviderTelegram
		return nil
	case IdentityProviderApple:
		*s = IdentityProviderApple
		return nil
	case IdentityProviderGoogle:
		*s = IdentityProviderGoogle
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/LinkedIdentity
type LinkedIdentity struct {
	Provider IdentityProvider `json:"provider"`
	LinkedAt time.Time        `json:"linkedAt"`
}

// GetProvider returns the value of Provider.
func (s *LinkedIdentity) GetProvider() IdentityProvider {
	return s.Provider
}

// GetLinkedAt returns the value of LinkedAt.
func (s *LinkedIdentity) GetLinkedAt() time.Time {
	return s.LinkedAt
}

// SetProvider sets the value of Provider.
func (s *LinkedIdentity) SetProvider(val IdentityProvider) {
	s.Provider = val
}

// SetLinkedAt sets the value of LinkedAt.
func (s *LinkedIdentity) SetLinkedAt(val time.Time) {
	s.LinkedAt = val
}

// Ref: #/components/schemas/Locale
type Locale string

const (
	LocaleRu Locale = "ru"
	LocaleEn Locale = "en"
)

// AllValues returns all Locale values.
func (Locale) AllValues() []Locale {
	return []Locale{
		LocaleRu,
		LocaleEn,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Locale) MarshalText() ([]byte, error) {
	switch s {
	case LocaleRu:
		return []byte(s), nil
	case LocaleEn:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Locale) UnmarshalText(data []byte) error {
	switch Locale(data) {
	case LocaleRu:
		*s = LocaleRu
		return nil
	case LocaleEn:
		*s = LocaleEn
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/LocalizedText
type LocalizedText struct {
	Ru string `json:"ru"`
	En string `json:"en"`
}

// GetRu returns the value of Ru.
func (s *LocalizedText) GetRu() string {
	return s.Ru
}

// GetEn returns the value of En.
func (s *LocalizedText) GetEn() string {
	return s.En
}

// SetRu sets the value of Ru.
func (s *LocalizedText) SetRu(val string) {
	s.Ru = val
}

// SetEn sets the value of En.
func (s *LocalizedText) SetEn(val string) {
	s.En = val
}

// NewNilActiveExam returns new NilActiveExam with value set to v.
func NewNilActiveExam(v ActiveExam) NilActiveExam {
	return NilActiveExam{
		Value: v,
	}
}

// NilActiveExam is nullable ActiveExam.
type NilActiveExam struct {
	Value ActiveExam
	Null  bool
}

// SetTo sets value to v.
func (o *NilActiveExam) SetTo(v ActiveExam) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilActiveExam) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilActiveExam) SetToNull() {
	o.Null = true
	var v ActiveExam
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilActiveExam) Get() (v ActiveExam, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilActiveExam) Or(d ActiveExam) ActiveExam {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptClientKind returns new OptClientKind with value set to v.
func NewOptClientKind(v ClientKind) OptClientKind {
	return OptClientKind{
		Value: v,
		Set:   true,
	}
}

// OptClientKind is optional ClientKind.
type OptClientKind struct {
	Value ClientKind
	Set   bool
}

// IsSet returns true if OptClientKind was set.
func (o OptClientKind) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptClientKind) Reset() {
	var v ClientKind
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptClientKind) SetTo(v ClientKind) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptClientKind) Get() (v ClientKind, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptClientKind) Or(d ClientKind) ClientKind {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDifficulty returns new OptDifficulty with value set to v.
func NewOptDifficulty(v Difficulty) OptDifficulty {
	return OptDifficulty{
		Value: v,
		Set:   true,
	}
}

// OptDifficulty is optional Difficulty.
type OptDifficulty struct {
	Value Difficulty
	Set   bool
}

// IsSet returns true if OptDifficulty was set.
func (o OptDifficulty) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDifficulty) Reset() {
	var v Difficulty
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDifficulty) SetTo(v Difficulty) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDifficulty) Get() (v Difficulty, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDifficulty) Or(d Difficulty) Difficulty {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptExam returns new OptExam with value set to v.
func NewOptExam(v Exam) OptExam {
	return OptExam{
		Value: v,
		Set:   true,
	}
}

// OptExam is optional Exam.
type OptExam struct {
	Value Exam
	Set   bool
}

// IsSet returns true if OptExam was set.
func (o OptExam) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptExam) Reset() {
	var v Exam
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptExam) SetTo(v Exam) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptExam) Get() (v Exam, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptExam) Or(d Exam) Exam {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptGivenAnswer returns new OptGivenAnswer with value set to v.
func NewOptGivenAnswer(v GivenAnswer) OptGivenAnswer {
	return OptGivenAnswer{
		Value: v,
		Set:   true,
	}
}

// OptGivenAnswer is optional GivenAnswer.
type OptGivenAnswer struct {
	Value GivenAnswer
	Set   bool
}

// IsSet returns true if OptGivenAnswer was set.
func (o OptGivenAnswer) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptGivenAnswer) Reset() {
	var v GivenAnswer
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptGivenAnswer) SetTo(v GivenAnswer) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptGivenAnswer) Get() (v GivenAnswer, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptGivenAnswer) Or(d GivenAnswer) GivenAnswer {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptLocale returns new OptLocale with value set to v.
func NewOptLocale(v Locale) OptLocale {
	return OptLocale{
		Value: v,
		Set:   true,
	}
}

// OptLocale is optional Locale.
type OptLocale struct {
	Value Locale
	Set   bool
}

// IsSet returns true if OptLocale was set.
func (o OptLocale) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptLocale) Reset() {
	var v Locale
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptLocale) SetTo(v Locale) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptLocale) Get() (v Locale, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptLocale) Or(d Locale) Locale {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRole returns new OptRole with value set to v.
func NewOptRole(v Role) OptRole {
	return OptRole{
		Value: v,
		Set:   true,
	}
}

// OptRole is optional Role.
type OptRole struct {
	Value Role
	Set   bool
}

// IsSet returns true if OptRole was set.
func (o OptRole) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRole) Reset() {
	var v Role
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRole) SetTo(v Role) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRole) Get() (v Role, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRole) Or(d Role) Role {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/OptionExplanation
type OptionExplanation struct {
	OptionId string `json:"optionId"`
	// Почему соблазняет и чем плох.
	Text LocalizedText `json:"text"`
}

// GetOptionId returns the value of OptionId.
func (s *OptionExplanation) GetOptionId() string {
	return s.OptionId
}

// GetText returns the value of Text.
func (s *OptionExplanation) GetText() LocalizedText {
	return s.Text
}

// SetOptionId sets the value of OptionId.
func (s *OptionExplanation) SetOptionId(val string) {
	s.OptionId = val
}

// SetText sets the value of Text.
func (s *OptionExplanation) SetText(val LocalizedText) {
	s.Text = val
}

// Ref: #/components/schemas/OptionGroup
type OptionGroup struct {
	Options []QuestionOption `json:"options"`
}

// GetOptions returns the value of Options.
func (s *OptionGroup) GetOptions() []QuestionOption {
	return s.Options
}

// SetOptions sets the value of Options.
func (s *OptionGroup) SetOptions(val []QuestionOption) {
	s.Options = val
}

// Ref: #/components/schemas/Question
type Question struct {
	ID           uuid.UUID     `json:"id"`
	QuestionType QuestionType  `json:"questionType"`
	Section      Section       `json:"section"`
	TopicId      string        `json:"topicId"`
	TopicTitle   LocalizedText `json:"topicTitle"`
	Difficulty   Difficulty    `json:"difficulty"`
	// Текст задания на английском. Пропуски Text Completion и Sentence
	// Equivalence — «___» по порядку групп вариантов.
	Prompt string `json:"prompt"`
	// Условие над величинами Quantitative Comparison (например, «0 < x < 1»).
	Condition OptString `json:"condition"`
	QuantityA OptString `json:"quantityA"`
	QuantityB OptString `json:"quantityB"`
	// Группа — один пропуск Text Completion; у остальных типов одна
	// группа.
	Groups []OptionGroup `json:"groups"`
	// Сколько вариантов выбрать в группе (Sentence Equivalence — 2).
	SelectCount int `json:"selectCount"`
	// Верные варианты. Приходит вместе с заданием: проверка
	// без сети идёт на устройстве; сервер проверяет ответ
	// сам и статистику клиенту не доверяет.
	Answer      []string    `json:"answer"`
	Explanation Explanation `json:"explanation"`
}

// GetID returns the value of ID.
func (s *Question) GetID() uuid.UUID {
	return s.ID
}

// GetQuestionType returns the value of QuestionType.
func (s *Question) GetQuestionType() QuestionType {
	return s.QuestionType
}

// GetSection returns the value of Section.
func (s *Question) GetSection() Section {
	return s.Section
}

// GetTopicId returns the value of TopicId.
func (s *Question) GetTopicId() string {
	return s.TopicId
}

// GetTopicTitle returns the value of TopicTitle.
func (s *Question) GetTopicTitle() LocalizedText {
	return s.TopicTitle
}

// GetDifficulty returns the value of Difficulty.
func (s *Question) GetDifficulty() Difficulty {
	return s.Difficulty
}

// GetPrompt returns the value of Prompt.
func (s *Question) GetPrompt() string {
	return s.Prompt
}

// GetCondition returns the value of Condition.
func (s *Question) GetCondition() OptString {
	return s.Condition
}

// GetQuantityA returns the value of QuantityA.
func (s *Question) GetQuantityA() OptString {
	return s.QuantityA
}

// GetQuantityB returns the value of QuantityB.
func (s *Question) GetQuantityB() OptString {
	return s.QuantityB
}

// GetGroups returns the value of Groups.
func (s *Question) GetGroups() []OptionGroup {
	return s.Groups
}

// GetSelectCount returns the value of SelectCount.
func (s *Question) GetSelectCount() int {
	return s.SelectCount
}

// GetAnswer returns the value of Answer.
func (s *Question) GetAnswer() []string {
	return s.Answer
}

// GetExplanation returns the value of Explanation.
func (s *Question) GetExplanation() Explanation {
	return s.Explanation
}

// SetID sets the value of ID.
func (s *Question) SetID(val uuid.UUID) {
	s.ID = val
}

// SetQuestionType sets the value of QuestionType.
func (s *Question) SetQuestionType(val QuestionType) {
	s.QuestionType = val
}

// SetSection sets the value of Section.
func (s *Question) SetSection(val Section) {
	s.Section = val
}

// SetTopicId sets the value of TopicId.
func (s *Question) SetTopicId(val string) {
	s.TopicId = val
}

// SetTopicTitle sets the value of TopicTitle.
func (s *Question) SetTopicTitle(val LocalizedText) {
	s.TopicTitle = val
}

// SetDifficulty sets the value of Difficulty.
func (s *Question) SetDifficulty(val Difficulty) {
	s.Difficulty = val
}

// SetPrompt sets the value of Prompt.
func (s *Question) SetPrompt(val string) {
	s.Prompt = val
}

// SetCondition sets the value of Condition.
func (s *Question) SetCondition(val OptString) {
	s.Condition = val
}

// SetQuantityA sets the value of QuantityA.
func (s *Question) SetQuantityA(val OptString) {
	s.QuantityA = val
}

// SetQuantityB sets the value of QuantityB.
func (s *Question) SetQuantityB(val OptString) {
	s.QuantityB = val
}

// SetGroups sets the value of Groups.
func (s *Question) SetGroups(val []OptionGroup) {
	s.Groups = val
}

// SetSelectCount sets the value of SelectCount.
func (s *Question) SetSelectCount(val int) {
	s.SelectCount = val
}

// SetAnswer sets the value of Answer.
func (s *Question) SetAnswer(val []string) {
	s.Answer = val
}

// SetExplanation sets the value of Explanation.
func (s *Question) SetExplanation(val Explanation) {
	s.Explanation = val
}

// Ref: #/components/schemas/QuestionOption
type QuestionOption struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

// GetID returns the value of ID.
func (s *QuestionOption) GetID() string {
	return s.ID
}

// GetText returns the value of Text.
func (s *QuestionOption) GetText() string {
	return s.Text
}

// SetID sets the value of ID.
func (s *QuestionOption) SetID(val string) {
	s.ID = val
}

// SetText sets the value of Text.
func (s *QuestionOption) SetText(val string) {
	s.Text = val
}

// Ref: #/components/schemas/QuestionReport
type QuestionReport struct {
	// Где ошибка — в задании, в ответе, в разборе, в переводе,
	// другое (макет R17).
	Kind       QuestionReportKind `json:"kind"`
	Text       OptString          `json:"text"`
	TrainingId OptUUID            `json:"trainingId"`
}

// GetKind returns the value of Kind.
func (s *QuestionReport) GetKind() QuestionReportKind {
	return s.Kind
}

// GetText returns the value of Text.
func (s *QuestionReport) GetText() OptString {
	return s.Text
}

// GetTrainingId returns the value of TrainingId.
func (s *QuestionReport) GetTrainingId() OptUUID {
	return s.TrainingId
}

// SetKind sets the value of Kind.
func (s *QuestionReport) SetKind(val QuestionReportKind) {
	s.Kind = val
}

// SetText sets the value of Text.
func (s *QuestionReport) SetText(val OptString) {
	s.Text = val
}

// SetTrainingId sets the value of TrainingId.
func (s *QuestionReport) SetTrainingId(val OptUUID) {
	s.TrainingId = val
}

// Где ошибка — в задании, в ответе, в разборе, в переводе,
// другое (макет R17).
type QuestionReportKind string

const (
	QuestionReportKindQuestion    QuestionReportKind = "question"
	QuestionReportKindAnswer      QuestionReportKind = "answer"
	QuestionReportKindExplanation QuestionReportKind = "explanation"
	QuestionReportKindTranslation QuestionReportKind = "translation"
	QuestionReportKindOther       QuestionReportKind = "other"
)

// AllValues returns all QuestionReportKind values.
func (QuestionReportKind) AllValues() []QuestionReportKind {
	return []QuestionReportKind{
		QuestionReportKindQuestion,
		QuestionReportKindAnswer,
		QuestionReportKindExplanation,
		QuestionReportKindTranslation,
		QuestionReportKindOther,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s QuestionReportKind) MarshalText() ([]byte, error) {
	switch s {
	case QuestionReportKindQuestion:
		return []byte(s), nil
	case QuestionReportKindAnswer:
		return []byte(s), nil
	case QuestionReportKindExplanation:
		return []byte(s), nil
	case QuestionReportKindTranslation:
		return []byte(s), nil
	case QuestionReportKindOther:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *QuestionReportKind) UnmarshalText(data []byte) error {
	switch QuestionReportKind(data) {
	case QuestionReportKindQuestion:
		*s = QuestionReportKindQuestion
		return nil
	case QuestionReportKindAnswer:
		*s = QuestionReportKindAnswer
		return nil
	case QuestionReportKindExplanation:
		*s = QuestionReportKindExplanation
		return nil
	case QuestionReportKindTranslation:
		*s = QuestionReportKindTranslation
		return nil
	case QuestionReportKindOther:
		*s = QuestionReportKindOther
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Первый срез тренировок — задания с выбором ответа
// (решение Даши 06.10.2026): Text Completion (1–3 пропуска), Sentence Equivalence
// (два ответа из шести), Quantitative Comparison, обычный выбор в
// математике. Reading Comprehension, ввод числа и несколько верных
// — следующими срезами.
// Ref: #/components/schemas/QuestionType
type QuestionType string

const (
	QuestionTypeTextCompletion         QuestionType = "text_completion"
	QuestionTypeSentenceEquivalence    QuestionType = "sentence_equivalence"
	QuestionTypeQuantitativeComparison QuestionType = "quantitative_comparison"
	QuestionTypeMultipleChoice         QuestionType = "multiple_choice"
)

// AllValues returns all QuestionType values.
func (QuestionType) AllValues() []QuestionType {
	return []QuestionType{
		QuestionTypeTextCompletion,
		QuestionTypeSentenceEquivalence,
		QuestionTypeQuantitativeComparison,
		QuestionTypeMultipleChoice,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s QuestionType) MarshalText() ([]byte, error) {
	switch s {
	case QuestionTypeTextCompletion:
		return []byte(s), nil
	case QuestionTypeSentenceEquivalence:
		return []byte(s), nil
	case QuestionTypeQuantitativeComparison:
		return []byte(s), nil
	case QuestionTypeMultipleChoice:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *QuestionType) UnmarshalText(data []byte) error {
	switch QuestionType(data) {
	case QuestionTypeTextCompletion:
		*s = QuestionTypeTextCompletion
		return nil
	case QuestionTypeSentenceEquivalence:
		*s = QuestionTypeSentenceEquivalence
		return nil
	case QuestionTypeQuantitativeComparison:
		*s = QuestionTypeQuantitativeComparison
		return nil
	case QuestionTypeMultipleChoice:
		*s = QuestionTypeMultipleChoice
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// ReportClientErrorNoContent is response for ReportClientError operation.
type ReportClientErrorNoContent struct{}

// ReportQuestionNoContent is response for ReportQuestion operation.
type ReportQuestionNoContent struct{}

// Ref: #/components/schemas/ReviewItem
type ReviewItem struct {
	ID    uuid.UUID      `json:"id"`
	Kind  ReviewItemKind `json:"kind"`
	Title string         `json:"title"`
}

// GetID returns the value of ID.
func (s *ReviewItem) GetID() uuid.UUID {
	return s.ID
}

// GetKind returns the value of Kind.
func (s *ReviewItem) GetKind() ReviewItemKind {
	return s.Kind
}

// GetTitle returns the value of Title.
func (s *ReviewItem) GetTitle() string {
	return s.Title
}

// SetID sets the value of ID.
func (s *ReviewItem) SetID(val uuid.UUID) {
	s.ID = val
}

// SetKind sets the value of Kind.
func (s *ReviewItem) SetKind(val ReviewItemKind) {
	s.Kind = val
}

// SetTitle sets the value of Title.
func (s *ReviewItem) SetTitle(val string) {
	s.Title = val
}

type ReviewItemKind string

const (
	ReviewItemKindQuestion    ReviewItemKind = "question"
	ReviewItemKindWord        ReviewItemKind = "word"
	ReviewItemKindTheory      ReviewItemKind = "theory"
	ReviewItemKindEssayPrompt ReviewItemKind = "essay_prompt"
)

// AllValues returns all ReviewItemKind values.
func (ReviewItemKind) AllValues() []ReviewItemKind {
	return []ReviewItemKind{
		ReviewItemKindQuestion,
		ReviewItemKindWord,
		ReviewItemKindTheory,
		ReviewItemKindEssayPrompt,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ReviewItemKind) MarshalText() ([]byte, error) {
	switch s {
	case ReviewItemKindQuestion:
		return []byte(s), nil
	case ReviewItemKindWord:
		return []byte(s), nil
	case ReviewItemKindTheory:
		return []byte(s), nil
	case ReviewItemKindEssayPrompt:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ReviewItemKind) UnmarshalText(data []byte) error {
	switch ReviewItemKind(data) {
	case ReviewItemKindQuestion:
		*s = ReviewItemKindQuestion
		return nil
	case ReviewItemKindWord:
		*s = ReviewItemKindWord
		return nil
	case ReviewItemKindTheory:
		*s = ReviewItemKindTheory
		return nil
	case ReviewItemKindEssayPrompt:
		*s = ReviewItemKindEssayPrompt
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ReviewQueue
type ReviewQueue struct {
	Items []ReviewItem `json:"items"`
}

// GetItems returns the value of Items.
func (s *ReviewQueue) GetItems() []ReviewItem {
	return s.Items
}

// SetItems sets the value of Items.
func (s *ReviewQueue) SetItems(val []ReviewItem) {
	s.Items = val
}

// Ref: #/components/schemas/Role
type Role string

const (
	RoleUser  Role = "user"
	RoleAdmin Role = "admin"
)

// AllValues returns all Role values.
func (Role) AllValues() []Role {
	return []Role{
		RoleUser,
		RoleAdmin,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Role) MarshalText() ([]byte, error) {
	switch s {
	case RoleUser:
		return []byte(s), nil
	case RoleAdmin:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Role) UnmarshalText(data []byte) error {
	switch Role(data) {
	case RoleUser:
		*s = RoleUser
		return nil
	case RoleAdmin:
		*s = RoleAdmin
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Section
type Section string

const (
	SectionVerbal    Section = "verbal"
	SectionQuant     Section = "quant"
	SectionWords     Section = "words"
	SectionEssay     Section = "essay"
	SectionReading   Section = "reading"
	SectionListening Section = "listening"
	SectionWriting   Section = "writing"
	SectionSpeaking  Section = "speaking"
)

// AllValues returns all Section values.
func (Section) AllValues() []Section {
	return []Section{
		SectionVerbal,
		SectionQuant,
		SectionWords,
		SectionEssay,
		SectionReading,
		SectionListening,
		SectionWriting,
		SectionSpeaking,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Section) MarshalText() ([]byte, error) {
	switch s {
	case SectionVerbal:
		return []byte(s), nil
	case SectionQuant:
		return []byte(s), nil
	case SectionWords:
		return []byte(s), nil
	case SectionEssay:
		return []byte(s), nil
	case SectionReading:
		return []byte(s), nil
	case SectionListening:
		return []byte(s), nil
	case SectionWriting:
		return []byte(s), nil
	case SectionSpeaking:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Section) UnmarshalText(data []byte) error {
	switch Section(data) {
	case SectionVerbal:
		*s = SectionVerbal
		return nil
	case SectionQuant:
		*s = SectionQuant
		return nil
	case SectionWords:
		*s = SectionWords
		return nil
	case SectionEssay:
		*s = SectionEssay
		return nil
	case SectionReading:
		*s = SectionReading
		return nil
	case SectionListening:
		*s = SectionListening
		return nil
	case SectionWriting:
		*s = SectionWriting
		return nil
	case SectionSpeaking:
		*s = SectionSpeaking
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Session
type Session struct {
	// Только при transport=bearer; хранить в Keychain / Keystore, в мини-аппе
	// — в памяти.
	Token OptString `json:"token"`
	// Когда сессия истечёт без активности.
	ExpiresAt time.Time `json:"expiresAt"`
	User      User      `json:"user"`
}

// GetToken returns the value of Token.
func (s *Session) GetToken() OptString {
	return s.Token
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *Session) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// GetUser returns the value of User.
func (s *Session) GetUser() User {
	return s.User
}

// SetToken sets the value of Token.
func (s *Session) SetToken(val OptString) {
	s.Token = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *Session) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}

// SetUser sets the value of User.
func (s *Session) SetUser(val User) {
	s.User = val
}

// SessionHeaders wraps Session with response headers.
type SessionHeaders struct {
	SetCookie OptString
	Response  Session
}

// GetSetCookie returns the value of SetCookie.
func (s *SessionHeaders) GetSetCookie() OptString {
	return s.SetCookie
}

// GetResponse returns the value of Response.
func (s *SessionHeaders) GetResponse() Session {
	return s.Response
}

// SetSetCookie sets the value of SetCookie.
func (s *SessionHeaders) SetSetCookie(val OptString) {
	s.SetCookie = val
}

// SetResponse sets the value of Response.
func (s *SessionHeaders) SetResponse(val Session) {
	s.Response = val
}

// Bearer — токен в теле (мини-апп, приложения); cookie — токен
// только в куке __Host-session (сайт, админка), в теле его нет.
// Ref: #/components/schemas/SessionTransport
type SessionTransport string

const (
	SessionTransportBearer SessionTransport = "bearer"
	SessionTransportCookie SessionTransport = "cookie"
)

// AllValues returns all SessionTransport values.
func (SessionTransport) AllValues() []SessionTransport {
	return []SessionTransport{
		SessionTransportBearer,
		SessionTransportCookie,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SessionTransport) MarshalText() ([]byte, error) {
	switch s {
	case SessionTransportBearer:
		return []byte(s), nil
	case SessionTransportCookie:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SessionTransport) UnmarshalText(data []byte) error {
	switch SessionTransport(data) {
	case SessionTransportBearer:
		*s = SessionTransportBearer
		return nil
	case SessionTransportCookie:
		*s = SessionTransportCookie
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// SignOutNoContent is response for SignOut operation.
type SignOutNoContent struct {
	SetCookie OptString
}

// GetSetCookie returns the value of SetCookie.
func (s *SignOutNoContent) GetSetCookie() OptString {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *SignOutNoContent) SetSetCookie(val OptString) {
	s.SetCookie = val
}

// Ref: #/components/schemas/StepState
type StepState string

const (
	StepStateDone    StepState = "done"
	StepStateCurrent StepState = "current"
	StepStateNext    StepState = "next"
)

// AllValues returns all StepState values.
func (StepState) AllValues() []StepState {
	return []StepState{
		StepStateDone,
		StepStateCurrent,
		StepStateNext,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s StepState) MarshalText() ([]byte, error) {
	switch s {
	case StepStateDone:
		return []byte(s), nil
	case StepStateCurrent:
		return []byte(s), nil
	case StepStateNext:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *StepState) UnmarshalText(data []byte) error {
	switch StepState(data) {
	case StepStateDone:
		*s = StepStateDone
		return nil
	case StepStateCurrent:
		*s = StepStateCurrent
		return nil
	case StepStateNext:
		*s = StepStateNext
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// SubmitTrainingAnswersNoContent is response for SubmitTrainingAnswers operation.
type SubmitTrainingAnswersNoContent struct{}

// Ref: #/components/schemas/TelegramMiniAppSignIn
type TelegramMiniAppSignIn struct {
	// Сырая строка initData от Telegram.
	InitData string `json:"initData"`
}

// GetInitData returns the value of InitData.
func (s *TelegramMiniAppSignIn) GetInitData() string {
	return s.InitData
}

// SetInitData sets the value of InitData.
func (s *TelegramMiniAppSignIn) SetInitData(val string) {
	s.InitData = val
}

// Ref: #/components/schemas/Today
type Today struct {
	Date  time.Time   `json:"date"`
	Steps []TodayStep `json:"steps"`
}

// GetDate returns the value of Date.
func (s *Today) GetDate() time.Time {
	return s.Date
}

// GetSteps returns the value of Steps.
func (s *Today) GetSteps() []TodayStep {
	return s.Steps
}

// SetDate sets the value of Date.
func (s *Today) SetDate(val time.Time) {
	s.Date = val
}

// SetSteps sets the value of Steps.
func (s *Today) SetSteps(val []TodayStep) {
	s.Steps = val
}

// Ref: #/components/schemas/TodayStep
type TodayStep struct {
	ID      string  `json:"id"`
	Section Section `json:"section"`
	// На языке интерфейса человека.
	Title   string    `json:"title"`
	Minutes int       `json:"minutes"`
	State   StepState `json:"state"`
}

// GetID returns the value of ID.
func (s *TodayStep) GetID() string {
	return s.ID
}

// GetSection returns the value of Section.
func (s *TodayStep) GetSection() Section {
	return s.Section
}

// GetTitle returns the value of Title.
func (s *TodayStep) GetTitle() string {
	return s.Title
}

// GetMinutes returns the value of Minutes.
func (s *TodayStep) GetMinutes() int {
	return s.Minutes
}

// GetState returns the value of State.
func (s *TodayStep) GetState() StepState {
	return s.State
}

// SetID sets the value of ID.
func (s *TodayStep) SetID(val string) {
	s.ID = val
}

// SetSection sets the value of Section.
func (s *TodayStep) SetSection(val Section) {
	s.Section = val
}

// SetTitle sets the value of Title.
func (s *TodayStep) SetTitle(val string) {
	s.Title = val
}

// SetMinutes sets the value of Minutes.
func (s *TodayStep) SetMinutes(val int) {
	s.Minutes = val
}

// SetState sets the value of State.
func (s *TodayStep) SetState(val StepState) {
	s.State = val
}

// Ref: #/components/schemas/TopicToReview
type TopicToReview struct {
	TopicId   string        `json:"topicId"`
	Title     LocalizedText `json:"title"`
	Mistakes  int           `json:"mistakes"`
	Positions []int         `json:"positions"`
}

// GetTopicId returns the value of TopicId.
func (s *TopicToReview) GetTopicId() string {
	return s.TopicId
}

// GetTitle returns the value of Title.
func (s *TopicToReview) GetTitle() LocalizedText {
	return s.Title
}

// GetMistakes returns the value of Mistakes.
func (s *TopicToReview) GetMistakes() int {
	return s.Mistakes
}

// GetPositions returns the value of Positions.
func (s *TopicToReview) GetPositions() []int {
	return s.Positions
}

// SetTopicId sets the value of TopicId.
func (s *TopicToReview) SetTopicId(val string) {
	s.TopicId = val
}

// SetTitle sets the value of Title.
func (s *TopicToReview) SetTitle(val LocalizedText) {
	s.Title = val
}

// SetMistakes sets the value of Mistakes.
func (s *TopicToReview) SetMistakes(val int) {
	s.Mistakes = val
}

// SetPositions sets the value of Positions.
func (s *TopicToReview) SetPositions(val []int) {
	s.Positions = val
}

// Ref: #/components/schemas/TrainingFinish
type TrainingFinish struct {
	FinishedAt time.Time `json:"finishedAt"`
	// Время «Проверки» вышло — оставшиеся вопросы «не
	// успел».
	TimedOut bool `json:"timedOut"`
}

// GetFinishedAt returns the value of FinishedAt.
func (s *TrainingFinish) GetFinishedAt() time.Time {
	return s.FinishedAt
}

// GetTimedOut returns the value of TimedOut.
func (s *TrainingFinish) GetTimedOut() bool {
	return s.TimedOut
}

// SetFinishedAt sets the value of FinishedAt.
func (s *TrainingFinish) SetFinishedAt(val time.Time) {
	s.FinishedAt = val
}

// SetTimedOut sets the value of TimedOut.
func (s *TrainingFinish) SetTimedOut(val bool) {
	s.TimedOut = val
}

// Ref: #/components/schemas/TrainingItem
type TrainingItem struct {
	Position int            `json:"position"`
	Question Question       `json:"question"`
	Answer   OptGivenAnswer `json:"answer"`
	// Проверка сервера; нет — ответа нет или он ещё не дошёл.
	Correct OptBool `json:"correct"`
}

// GetPosition returns the value of Position.
func (s *TrainingItem) GetPosition() int {
	return s.Position
}

// GetQuestion returns the value of Question.
func (s *TrainingItem) GetQuestion() Question {
	return s.Question
}

// GetAnswer returns the value of Answer.
func (s *TrainingItem) GetAnswer() OptGivenAnswer {
	return s.Answer
}

// GetCorrect returns the value of Correct.
func (s *TrainingItem) GetCorrect() OptBool {
	return s.Correct
}

// SetPosition sets the value of Position.
func (s *TrainingItem) SetPosition(val int) {
	s.Position = val
}

// SetQuestion sets the value of Question.
func (s *TrainingItem) SetQuestion(val Question) {
	s.Question = val
}

// SetAnswer sets the value of Answer.
func (s *TrainingItem) SetAnswer(val OptGivenAnswer) {
	s.Answer = val
}

// SetCorrect sets the value of Correct.
func (s *TrainingItem) SetCorrect(val OptBool) {
	s.Correct = val
}

// Practice — разбор после каждого вопроса, без таймера,
// вместо пропуска «Не знаю»; check — разбор в конце, таймер
// темпа экзамена, пропустить и вернуться можно, время
// вышло — сессия кончилась.
// Ref: #/components/schemas/TrainingMode
type TrainingMode string

const (
	TrainingModePractice TrainingMode = "practice"
	TrainingModeCheck    TrainingMode = "check"
)

// AllValues returns all TrainingMode values.
func (TrainingMode) AllValues() []TrainingMode {
	return []TrainingMode{
		TrainingModePractice,
		TrainingModeCheck,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TrainingMode) MarshalText() ([]byte, error) {
	switch s {
	case TrainingModePractice:
		return []byte(s), nil
	case TrainingModeCheck:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TrainingMode) UnmarshalText(data []byte) error {
	switch TrainingMode(data) {
	case TrainingModePractice:
		*s = TrainingModePractice
		return nil
	case TrainingModeCheck:
		*s = TrainingModeCheck
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/TrainingOptions
type TrainingOptions struct {
	Types   []TrainingType   `json:"types"`
	Presets []TrainingPreset `json:"presets"`
	// Больше этого числа вопросов в одной тренировке не
	// бывает.
	MaxQuestions int `json:"maxQuestions"`
}

// GetTypes returns the value of Types.
func (s *TrainingOptions) GetTypes() []TrainingType {
	return s.Types
}

// GetPresets returns the value of Presets.
func (s *TrainingOptions) GetPresets() []TrainingPreset {
	return s.Presets
}

// GetMaxQuestions returns the value of MaxQuestions.
func (s *TrainingOptions) GetMaxQuestions() int {
	return s.MaxQuestions
}

// SetTypes sets the value of Types.
func (s *TrainingOptions) SetTypes(val []TrainingType) {
	s.Types = val
}

// SetPresets sets the value of Presets.
func (s *TrainingOptions) SetPresets(val []TrainingPreset) {
	s.Presets = val
}

// SetMaxQuestions sets the value of MaxQuestions.
func (s *TrainingOptions) SetMaxQuestions(val int) {
	s.MaxQuestions = val
}

// Ref: #/components/schemas/TrainingPreset
type TrainingPreset struct {
	// Открытый список, не enum: новые виды появятся без
	// обновления приложений, а клиент пропускает
	// незнакомые. Сейчас — last («Как в прошлый раз») и timed
	// («Проверка на время»: все доступные типы раздела, 12
	// вопросов, как секция экзамена); «Мои ошибки» и «Слабая
	// тема» — с фичей «что повторить».
	Kind    string          `json:"kind"`
	Request TrainingRequest `json:"request"`
}

// GetKind returns the value of Kind.
func (s *TrainingPreset) GetKind() string {
	return s.Kind
}

// GetRequest returns the value of Request.
func (s *TrainingPreset) GetRequest() TrainingRequest {
	return s.Request
}

// SetKind sets the value of Kind.
func (s *TrainingPreset) SetKind(val string) {
	s.Kind = val
}

// SetRequest sets the value of Request.
func (s *TrainingPreset) SetRequest(val TrainingRequest) {
	s.Request = val
}

// Ref: #/components/schemas/TrainingRequest
type TrainingRequest struct {
	Exam    Exam    `json:"exam"`
	Section Section `json:"section"`
	// Конструктор даёт один тип; «Проверка на время» — все
	// типы раздела вперемешку (макет R16).
	QuestionTypes []QuestionType `json:"questionTypes"`
	// Пусто или нет — все темы.
	TopicIds   []string      `json:"topicIds"`
	Difficulty OptDifficulty `json:"difficulty"`
	Count      int           `json:"count"`
	Mode       TrainingMode  `json:"mode"`
}

// GetExam returns the value of Exam.
func (s *TrainingRequest) GetExam() Exam {
	return s.Exam
}

// GetSection returns the value of Section.
func (s *TrainingRequest) GetSection() Section {
	return s.Section
}

// GetQuestionTypes returns the value of QuestionTypes.
func (s *TrainingRequest) GetQuestionTypes() []QuestionType {
	return s.QuestionTypes
}

// GetTopicIds returns the value of TopicIds.
func (s *TrainingRequest) GetTopicIds() []string {
	return s.TopicIds
}

// GetDifficulty returns the value of Difficulty.
func (s *TrainingRequest) GetDifficulty() OptDifficulty {
	return s.Difficulty
}

// GetCount returns the value of Count.
func (s *TrainingRequest) GetCount() int {
	return s.Count
}

// GetMode returns the value of Mode.
func (s *TrainingRequest) GetMode() TrainingMode {
	return s.Mode
}

// SetExam sets the value of Exam.
func (s *TrainingRequest) SetExam(val Exam) {
	s.Exam = val
}

// SetSection sets the value of Section.
func (s *TrainingRequest) SetSection(val Section) {
	s.Section = val
}

// SetQuestionTypes sets the value of QuestionTypes.
func (s *TrainingRequest) SetQuestionTypes(val []QuestionType) {
	s.QuestionTypes = val
}

// SetTopicIds sets the value of TopicIds.
func (s *TrainingRequest) SetTopicIds(val []string) {
	s.TopicIds = val
}

// SetDifficulty sets the value of Difficulty.
func (s *TrainingRequest) SetDifficulty(val OptDifficulty) {
	s.Difficulty = val
}

// SetCount sets the value of Count.
func (s *TrainingRequest) SetCount(val int) {
	s.Count = val
}

// SetMode sets the value of Mode.
func (s *TrainingRequest) SetMode(val TrainingMode) {
	s.Mode = val
}

// Ref: #/components/schemas/TrainingSession
type TrainingSession struct {
	ID uuid.UUID `json:"id"`
	// Необязательное только для чтения сохранённых сессий
	// старого формата; сервер возвращает всегда.
	Exam          OptExam        `json:"exam"`
	Mode          TrainingMode   `json:"mode"`
	Section       Section        `json:"section"`
	QuestionTypes []QuestionType `json:"questionTypes"`
	StartedAt     time.Time      `json:"startedAt"`
	// Только у «Проверки» — темп секции экзамена.
	TimeLimitSeconds OptInt         `json:"timeLimitSeconds"`
	FinishedAt       OptDateTime    `json:"finishedAt"`
	Items            []TrainingItem `json:"items"`
}

// GetID returns the value of ID.
func (s *TrainingSession) GetID() uuid.UUID {
	return s.ID
}

// GetExam returns the value of Exam.
func (s *TrainingSession) GetExam() OptExam {
	return s.Exam
}

// GetMode returns the value of Mode.
func (s *TrainingSession) GetMode() TrainingMode {
	return s.Mode
}

// GetSection returns the value of Section.
func (s *TrainingSession) GetSection() Section {
	return s.Section
}

// GetQuestionTypes returns the value of QuestionTypes.
func (s *TrainingSession) GetQuestionTypes() []QuestionType {
	return s.QuestionTypes
}

// GetStartedAt returns the value of StartedAt.
func (s *TrainingSession) GetStartedAt() time.Time {
	return s.StartedAt
}

// GetTimeLimitSeconds returns the value of TimeLimitSeconds.
func (s *TrainingSession) GetTimeLimitSeconds() OptInt {
	return s.TimeLimitSeconds
}

// GetFinishedAt returns the value of FinishedAt.
func (s *TrainingSession) GetFinishedAt() OptDateTime {
	return s.FinishedAt
}

// GetItems returns the value of Items.
func (s *TrainingSession) GetItems() []TrainingItem {
	return s.Items
}

// SetID sets the value of ID.
func (s *TrainingSession) SetID(val uuid.UUID) {
	s.ID = val
}

// SetExam sets the value of Exam.
func (s *TrainingSession) SetExam(val OptExam) {
	s.Exam = val
}

// SetMode sets the value of Mode.
func (s *TrainingSession) SetMode(val TrainingMode) {
	s.Mode = val
}

// SetSection sets the value of Section.
func (s *TrainingSession) SetSection(val Section) {
	s.Section = val
}

// SetQuestionTypes sets the value of QuestionTypes.
func (s *TrainingSession) SetQuestionTypes(val []QuestionType) {
	s.QuestionTypes = val
}

// SetStartedAt sets the value of StartedAt.
func (s *TrainingSession) SetStartedAt(val time.Time) {
	s.StartedAt = val
}

// SetTimeLimitSeconds sets the value of TimeLimitSeconds.
func (s *TrainingSession) SetTimeLimitSeconds(val OptInt) {
	s.TimeLimitSeconds = val
}

// SetFinishedAt sets the value of FinishedAt.
func (s *TrainingSession) SetFinishedAt(val OptDateTime) {
	s.FinishedAt = val
}

// SetItems sets the value of Items.
func (s *TrainingSession) SetItems(val []TrainingItem) {
	s.Items = val
}

// Ref: #/components/schemas/TrainingSummary
type TrainingSummary struct {
	Correct int `json:"correct"`
	Total   int `json:"total"`
	// Без ответа — «Не знаю», пропущенные и не успел.
	Unanswered      int `json:"unanswered"`
	DurationSeconds int `json:"durationSeconds"`
	// 1–3 темы, где больше всего ошибок, — «Что повторить».
	Review []TopicToReview `json:"review"`
}

// GetCorrect returns the value of Correct.
func (s *TrainingSummary) GetCorrect() int {
	return s.Correct
}

// GetTotal returns the value of Total.
func (s *TrainingSummary) GetTotal() int {
	return s.Total
}

// GetUnanswered returns the value of Unanswered.
func (s *TrainingSummary) GetUnanswered() int {
	return s.Unanswered
}

// GetDurationSeconds returns the value of DurationSeconds.
func (s *TrainingSummary) GetDurationSeconds() int {
	return s.DurationSeconds
}

// GetReview returns the value of Review.
func (s *TrainingSummary) GetReview() []TopicToReview {
	return s.Review
}

// SetCorrect sets the value of Correct.
func (s *TrainingSummary) SetCorrect(val int) {
	s.Correct = val
}

// SetTotal sets the value of Total.
func (s *TrainingSummary) SetTotal(val int) {
	s.Total = val
}

// SetUnanswered sets the value of Unanswered.
func (s *TrainingSummary) SetUnanswered(val int) {
	s.Unanswered = val
}

// SetDurationSeconds sets the value of DurationSeconds.
func (s *TrainingSummary) SetDurationSeconds(val int) {
	s.DurationSeconds = val
}

// SetReview sets the value of Review.
func (s *TrainingSummary) SetReview(val []TopicToReview) {
	s.Review = val
}

// Ref: #/components/schemas/TrainingTopic
type TrainingTopic struct {
	ID        string           `json:"id"`
	Title     LocalizedText    `json:"title"`
	Available DifficultyCounts `json:"available"`
}

// GetID returns the value of ID.
func (s *TrainingTopic) GetID() string {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *TrainingTopic) GetTitle() LocalizedText {
	return s.Title
}

// GetAvailable returns the value of Available.
func (s *TrainingTopic) GetAvailable() DifficultyCounts {
	return s.Available
}

// SetID sets the value of ID.
func (s *TrainingTopic) SetID(val string) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *TrainingTopic) SetTitle(val LocalizedText) {
	s.Title = val
}

// SetAvailable sets the value of Available.
func (s *TrainingTopic) SetAvailable(val DifficultyCounts) {
	s.Available = val
}

// Ref: #/components/schemas/TrainingType
type TrainingType struct {
	Section      Section      `json:"section"`
	QuestionType QuestionType `json:"questionType"`
	// Темп экзамена на вопрос (Verbal — 90 с, Quant — 105 с): время
	// «Проверки» и оценка «~12 мин» на кнопке.
	PaceSeconds int             `json:"paceSeconds"`
	Topics      []TrainingTopic `json:"topics"`
}

// GetSection returns the value of Section.
func (s *TrainingType) GetSection() Section {
	return s.Section
}

// GetQuestionType returns the value of QuestionType.
func (s *TrainingType) GetQuestionType() QuestionType {
	return s.QuestionType
}

// GetPaceSeconds returns the value of PaceSeconds.
func (s *TrainingType) GetPaceSeconds() int {
	return s.PaceSeconds
}

// GetTopics returns the value of Topics.
func (s *TrainingType) GetTopics() []TrainingTopic {
	return s.Topics
}

// SetSection sets the value of Section.
func (s *TrainingType) SetSection(val Section) {
	s.Section = val
}

// SetQuestionType sets the value of QuestionType.
func (s *TrainingType) SetQuestionType(val QuestionType) {
	s.QuestionType = val
}

// SetPaceSeconds sets the value of PaceSeconds.
func (s *TrainingType) SetPaceSeconds(val int) {
	s.PaceSeconds = val
}

// SetTopics sets the value of Topics.
func (s *TrainingType) SetTopics(val []TrainingTopic) {
	s.Topics = val
}

// Ref: #/components/schemas/User
type User struct {
	ID         uuid.UUID        `json:"id"`
	Name       string           `json:"name"`
	Role       Role             `json:"role"`
	Locale     Locale           `json:"locale"`
	ActiveExam NilActiveExam    `json:"activeExam"`
	Identities []LinkedIdentity `json:"identities"`
}

// GetID returns the value of ID.
func (s *User) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *User) GetName() string {
	return s.Name
}

// GetRole returns the value of Role.
func (s *User) GetRole() Role {
	return s.Role
}

// GetLocale returns the value of Locale.
func (s *User) GetLocale() Locale {
	return s.Locale
}

// GetActiveExam returns the value of ActiveExam.
func (s *User) GetActiveExam() NilActiveExam {
	return s.ActiveExam
}

// GetIdentities returns the value of Identities.
func (s *User) GetIdentities() []LinkedIdentity {
	return s.Identities
}

// SetID sets the value of ID.
func (s *User) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *User) SetName(val string) {
	s.Name = val
}

// SetRole sets the value of Role.
func (s *User) SetRole(val Role) {
	s.Role = val
}

// SetLocale sets the value of Locale.
func (s *User) SetLocale(val Locale) {
	s.Locale = val
}

// SetActiveExam sets the value of ActiveExam.
func (s *User) SetActiveExam(val NilActiveExam) {
	s.ActiveExam = val
}

// SetIdentities sets the value of Identities.
func (s *User) SetIdentities(val []LinkedIdentity) {
	s.Identities = val
}
