// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetHealthOperation                   OperationName = "GetHealth"
	GetMeOperation                       OperationName = "GetMe"
	GetReviewQueueOperation              OperationName = "GetReviewQueue"
	GetTodayOperation                    OperationName = "GetToday"
	ReportClientErrorOperation           OperationName = "ReportClientError"
	SignInForDevelopmentOperation        OperationName = "SignInForDevelopment"
	SignInWithAuthorizationCodeOperation OperationName = "SignInWithAuthorizationCode"
	SignInWithIdTokenOperation           OperationName = "SignInWithIdToken"
	SignInWithTelegramMiniAppOperation   OperationName = "SignInWithTelegramMiniApp"
	SignOutOperation                     OperationName = "SignOut"
)
