// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn7AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn16AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn21AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn19AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn18AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn20AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn11AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn6AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn14AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn9AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn22AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn10AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn2AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn24AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn3AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [1]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/"

			if l := len("/api/"); len(elem) >= l && elem[0:l] == "/api/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "a"

				if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'd': // Prefix: "dmin/review-queue"

					if l := len("dmin/review-queue"); len(elem) >= l && elem[0:l] == "dmin/review-queue" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetReviewQueueRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn7AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'u': // Prefix: "uth/"

					if l := len("uth/"); len(elem) >= l && elem[0:l] == "uth/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'd': // Prefix: "dev"

						if l := len("dev"); len(elem) >= l && elem[0:l] == "dev" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleSignInForDevelopmentRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn16AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'l': // Prefix: "logout"

						if l := len("logout"); len(elem) >= l && elem[0:l] == "logout" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleSignOutRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn21AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'o': // Prefix: "oidc"

						if l := len("oidc"); len(elem) >= l && elem[0:l] == "oidc" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "POST":
								s.handleSignInWithIdTokenRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn19AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/code"

							if l := len("/code"); len(elem) >= l && elem[0:l] == "/code" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleSignInWithAuthorizationCodeRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn18AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 't': // Prefix: "telegram-mini-app"

						if l := len("telegram-mini-app"); len(elem) >= l && elem[0:l] == "telegram-mini-app" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleSignInWithTelegramMiniAppRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn20AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'c': // Prefix: "client-errors"

				if l := len("client-errors"); len(elem) >= l && elem[0:l] == "client-errors" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleReportClientErrorRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "POST",
							allowedHeaders: rn11AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'h': // Prefix: "health"

				if l := len("health"); len(elem) >= l && elem[0:l] == "health" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetHealthRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'm': // Prefix: "me"

				if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetMeRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: rn6AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'q': // Prefix: "questions/"

				if l := len("questions/"); len(elem) >= l && elem[0:l] == "questions/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "questionId"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/reports"

					if l := len("/reports"); len(elem) >= l && elem[0:l] == "/reports" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleReportQuestionRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn14AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 't': // Prefix: "t"

				if l := len("t"); len(elem) >= l && elem[0:l] == "t" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'o': // Prefix: "oday"

					if l := len("oday"); len(elem) >= l && elem[0:l] == "oday" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetTodayRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn9AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'r': // Prefix: "rainings"

					if l := len("rainings"); len(elem) >= l && elem[0:l] == "rainings" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "POST":
							s.handleStartTrainingRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn22AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'o': // Prefix: "options"
							origElem := elem
							if l := len("options"); len(elem) >= l && elem[0:l] == "options" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetTrainingOptionsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn10AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

							elem = origElem
						}
						// Param: "trainingId"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleGetTrainingRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn2AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'a': // Prefix: "answers"

								if l := len("answers"); len(elem) >= l && elem[0:l] == "answers" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleSubmitTrainingAnswersRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn24AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'f': // Prefix: "finish"

								if l := len("finish"); len(elem) >= l && elem[0:l] == "finish" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleFinishTrainingRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn3AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/"

			if l := len("/api/"); len(elem) >= l && elem[0:l] == "/api/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "a"

				if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'd': // Prefix: "dmin/review-queue"

					if l := len("dmin/review-queue"); len(elem) >= l && elem[0:l] == "dmin/review-queue" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = GetReviewQueueOperation
							r.summary = "Очередь контента на проверку Даши (админка)"
							r.operationID = "getReviewQueue"
							r.operationGroup = ""
							r.pathPattern = "/api/admin/review-queue"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'u': // Prefix: "uth/"

					if l := len("uth/"); len(elem) >= l && elem[0:l] == "uth/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'd': // Prefix: "dev"

						if l := len("dev"); len(elem) >= l && elem[0:l] == "dev" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = SignInForDevelopmentOperation
								r.summary = "Вход подменой — локально, в тестах и на стенде; в бою 404"
								r.operationID = "signInForDevelopment"
								r.operationGroup = ""
								r.pathPattern = "/api/auth/dev"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'l': // Prefix: "logout"

						if l := len("logout"); len(elem) >= l && elem[0:l] == "logout" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = SignOutOperation
								r.summary = "Выйти на этом устройстве — сессия удаляется сразу"
								r.operationID = "signOut"
								r.operationGroup = ""
								r.pathPattern = "/api/auth/logout"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'o': // Prefix: "oidc"

						if l := len("oidc"); len(elem) >= l && elem[0:l] == "oidc" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "POST":
								r.name = SignInWithIdTokenOperation
								r.summary = "Вход по id_token Apple или Google, полученному на устройстве"
								r.operationID = "signInWithIdToken"
								r.operationGroup = ""
								r.pathPattern = "/api/auth/oidc"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/code"

							if l := len("/code"); len(elem) >= l && elem[0:l] == "/code" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = SignInWithAuthorizationCodeOperation
									r.summary = "Вход по коду авторизации (Telegram везде, Apple на сайте и Android)"
									r.operationID = "signInWithAuthorizationCode"
									r.operationGroup = ""
									r.pathPattern = "/api/auth/oidc/code"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					case 't': // Prefix: "telegram-mini-app"

						if l := len("telegram-mini-app"); len(elem) >= l && elem[0:l] == "telegram-mini-app" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = SignInWithTelegramMiniAppOperation
								r.summary = "Вход из мини-аппа по initData (подпись проверяется ключом бота)"
								r.operationID = "signInWithTelegramMiniApp"
								r.operationGroup = ""
								r.pathPattern = "/api/auth/telegram-mini-app"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'c': // Prefix: "client-errors"

				if l := len("client-errors"); len(elem) >= l && elem[0:l] == "client-errors" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "POST":
						r.name = ReportClientErrorOperation
						r.summary = "Ошибка на клиенте — в таблицу client_errors"
						r.operationID = "reportClientError"
						r.operationGroup = ""
						r.pathPattern = "/api/client-errors"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'h': // Prefix: "health"

				if l := len("health"); len(elem) >= l && elem[0:l] == "health" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetHealthOperation
						r.summary = "Жив ли сервер и какая сборка (сверка после выкладки)"
						r.operationID = "getHealth"
						r.operationGroup = ""
						r.pathPattern = "/api/health"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'm': // Prefix: "me"

				if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetMeOperation
						r.summary = "Кто вошёл"
						r.operationID = "getMe"
						r.operationGroup = ""
						r.pathPattern = "/api/me"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'q': // Prefix: "questions/"

				if l := len("questions/"); len(elem) >= l && elem[0:l] == "questions/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "questionId"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/reports"

					if l := len("/reports"); len(elem) >= l && elem[0:l] == "/reports" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = ReportQuestionOperation
							r.summary = "«Сообщить об ошибке» в задании — в очередь админки"
							r.operationID = "reportQuestion"
							r.operationGroup = ""
							r.pathPattern = "/api/questions/{questionId}/reports"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 't': // Prefix: "t"

				if l := len("t"); len(elem) >= l && elem[0:l] == "t" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'o': // Prefix: "oday"

					if l := len("oday"); len(elem) >= l && elem[0:l] == "oday" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = GetTodayOperation
							r.summary = "Лента шагов на сегодня (экран «Сегодня»)"
							r.operationID = "getToday"
							r.operationGroup = ""
							r.pathPattern = "/api/today"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'r': // Prefix: "rainings"

					if l := len("rainings"); len(elem) >= l && elem[0:l] == "rainings" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "POST":
							r.name = StartTrainingOperation
							r.summary = "Начать тренировку — сессия со всеми заданиями и разборами сразу"
							r.operationID = "startTraining"
							r.operationGroup = ""
							r.pathPattern = "/api/trainings"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'o': // Prefix: "options"
							origElem := elem
							if l := len("options"); len(elem) >= l && elem[0:l] == "options" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetTrainingOptionsOperation
									r.summary = "Что можно собрать в конструкторе тренировки (макеты R1, R2)"
									r.operationID = "getTrainingOptions"
									r.operationGroup = ""
									r.pathPattern = "/api/trainings/options"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

							elem = origElem
						}
						// Param: "trainingId"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = GetTrainingOperation
								r.summary = "Своя тренировка — продолжить с того же вопроса или посмотреть разбор"
								r.operationID = "getTraining"
								r.operationGroup = ""
								r.pathPattern = "/api/trainings/{trainingId}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'a': // Prefix: "answers"

								if l := len("answers"); len(elem) >= l && elem[0:l] == "answers" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = SubmitTrainingAnswersOperation
										r.summary = "Ответы, накопленные на устройстве (в том числе без сети)"
										r.operationID = "submitTrainingAnswers"
										r.operationGroup = ""
										r.pathPattern = "/api/trainings/{trainingId}/answers"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'f': // Prefix: "finish"

								if l := len("finish"); len(elem) >= l && elem[0:l] == "finish" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = FinishTrainingOperation
										r.summary = "Закончить тренировку — итог и что повторить (макет R15)"
										r.operationID = "finishTraining"
										r.operationGroup = ""
										r.pathPattern = "/api/trainings/{trainingId}/finish"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					}

				}

			}

		}
	}
	return r, false
}
