// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// FinishTrainingParams is parameters of finishTraining operation.
type FinishTrainingParams struct {
	TrainingId uuid.UUID
}

func unpackFinishTrainingParams(packed middleware.Parameters) (params FinishTrainingParams) {
	{
		key := middleware.ParameterKey{
			Name: "trainingId",
			In:   "path",
		}
		params.TrainingId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeFinishTrainingParams(args [1]string, argsEscaped bool, r *http.Request) (params FinishTrainingParams, _ error) {
	// Decode path: trainingId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "trainingId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TrainingId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "trainingId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetTrainingParams is parameters of getTraining operation.
type GetTrainingParams struct {
	TrainingId uuid.UUID
}

func unpackGetTrainingParams(packed middleware.Parameters) (params GetTrainingParams) {
	{
		key := middleware.ParameterKey{
			Name: "trainingId",
			In:   "path",
		}
		params.TrainingId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetTrainingParams(args [1]string, argsEscaped bool, r *http.Request) (params GetTrainingParams, _ error) {
	// Decode path: trainingId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "trainingId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TrainingId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "trainingId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetTrainingOptionsParams is parameters of getTrainingOptions operation.
type GetTrainingOptionsParams struct {
	// Типы заданий, которые клиент умеет показывать. Других
	// сервер не присылает ни в списке, ни в наборах: новый тип
	// на сервере не ломает уже установленные версии
	// приложений.
	Types []QuestionType `json:",omitempty"`
}

func unpackGetTrainingOptionsParams(packed middleware.Parameters) (params GetTrainingOptionsParams) {
	{
		key := middleware.ParameterKey{
			Name: "types",
			In:   "query",
		}
		params.Types = packed[key].([]QuestionType)
	}
	return params
}

func decodeGetTrainingOptionsParams(args [0]string, argsEscaped bool, r *http.Request) (params GetTrainingOptionsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: types.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "types",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				params.Types = nil
				return d.DecodeArray(func(d uri.Decoder) error {
					var paramsDotTypesVal QuestionType
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotTypesVal = QuestionType(c)
						return nil
					}(); err != nil {
						return err
					}
					params.Types = append(params.Types, paramsDotTypesVal)
					return nil
				})
			}); err != nil {
				return err
			}
			if err := func() error {
				if params.Types == nil {
					return errors.New("nil is invalid value")
				}
				if err := (validate.Array{
					MinLength:    1,
					MinLengthSet: true,
					MaxLength:    20,
					MaxLengthSet: true,
				}).ValidateLength(len(params.Types)); err != nil {
					return errors.Wrap(err, "array")
				}
				var failures []validate.FieldError
				for i, elem := range params.Types {
					if err := func() error {
						if err := elem.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						failures = append(failures, validate.FieldError{
							Name:  fmt.Sprintf("[%d]", i),
							Error: err,
						})
					}
				}
				if len(failures) > 0 {
					return &validate.Error{Fields: failures}
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "types",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ReportQuestionParams is parameters of reportQuestion operation.
type ReportQuestionParams struct {
	QuestionId uuid.UUID
}

func unpackReportQuestionParams(packed middleware.Parameters) (params ReportQuestionParams) {
	{
		key := middleware.ParameterKey{
			Name: "questionId",
			In:   "path",
		}
		params.QuestionId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeReportQuestionParams(args [1]string, argsEscaped bool, r *http.Request) (params ReportQuestionParams, _ error) {
	// Decode path: questionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "questionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.QuestionId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "questionId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SubmitTrainingAnswersParams is parameters of submitTrainingAnswers operation.
type SubmitTrainingAnswersParams struct {
	TrainingId uuid.UUID
}

func unpackSubmitTrainingAnswersParams(packed middleware.Parameters) (params SubmitTrainingAnswersParams) {
	{
		key := middleware.ParameterKey{
			Name: "trainingId",
			In:   "path",
		}
		params.TrainingId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeSubmitTrainingAnswersParams(args [1]string, argsEscaped bool, r *http.Request) (params SubmitTrainingAnswersParams, _ error) {
	// Decode path: trainingId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "trainingId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TrainingId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "trainingId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
